import { drizzle } from 'drizzle-orm/d1';
import * as schema from '$lib/server/db/schema';
import { recurringExpenses, expenseTemplates, expenses } from '$lib/server/db/schema';
import { and, eq, isNull } from 'drizzle-orm';
import { parseISO, formatISO } from 'date-fns';
import { UTCDate } from '@date-fns/utc';
import { updateAuditFields } from '$lib/server/utils/audit';
import { requireVaultPermission } from '$lib/server/utils/vaultPermissions';
import { requireVaultEntitlement } from '$lib/server/utils/entitlements';
import {
    computeNextOccurrence,
    type ScheduleUnit,
} from '$lib/utils/recurringSchedule';
import {
    attachFundToExpense,
    detachFundFromExpense,
    applyFundAmountDelta,
} from '$lib/server/api/funds/fundExpenseHelpers';
import type { UpdateRecurringExpenseWithTemplateRequest } from '$lib/schemas/recurringExpenses';

/**
 * Edit a recurring rule and its backing template atomically. Optionally
 * propagates editable changes to every expense already generated by the rule
 * (amount + fund re-wiring included).
 */
export const updateRecurringExpenseWithTemplate = async (
    session: App.AuthSession,
    data: UpdateRecurringExpenseWithTemplateRequest,
    env: Cloudflare.Env,
) => {
    const client = drizzle(env.DB, { schema });
    const userId = session.user.id;

    await requireVaultPermission(session, data.vaultId, 'canManageRecurring', env);

    const [existing] = await client
        .select()
        .from(recurringExpenses)
        .where(
            and(
                eq(recurringExpenses.id, data.id),
                eq(recurringExpenses.vaultId, data.vaultId),
                isNull(recurringExpenses.deletedAt),
            ),
        )
        .limit(1);
    if (!existing) throw new Error('Recurring expense not found');

    // Entitlement re-checks for upgrades
    if (data.scheduleInterval > 1 && existing.scheduleInterval <= 1) {
        await requireVaultEntitlement(session, data.vaultId, 'recurring:custom_interval', env);
    }
    if (data.generationMode === 'auto' && existing.generationMode !== 'auto') {
        await requireVaultEntitlement(session, data.vaultId, 'recurring:auto_generation', env);
    }

    // Recompute nextOccurrenceAt if the schedule shape changed and the rule is active.
    const scheduleChanged =
        data.scheduleUnit !== existing.scheduleUnit ||
        data.scheduleInterval !== existing.scheduleInterval ||
        data.anchorDate !== existing.anchorDate;

    let nextOccurrenceAt = existing.nextOccurrenceAt;
    if (scheduleChanged && existing.status === 'active') {
        const anchor = parseISO(data.anchorDate);
        const now = new UTCDate();
        const n =
            anchor.getTime() > now.getTime()
                ? anchor
                : computeNextOccurrence(
                      anchor,
                      data.scheduleUnit as ScheduleUnit,
                      data.scheduleInterval,
                      now,
                  );
        nextOccurrenceAt = formatISO(new UTCDate(n));
    }

    const audit = updateAuditFields({ userId });

    // Template + rule update in one batch.
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const batchOps: any[] = [
        client
            .update(expenseTemplates)
            .set({
                name: data.name,
                icon: data.icon ?? '🔁',
                iconType: 'emoji',
                defaultNote: data.defaultNote ?? null,
                defaultAmount: data.defaultAmount,
                defaultCategoryName: data.defaultCategoryName,
                defaultPaymentType: data.defaultPaymentType ?? 'cash',
                defaultPaidBy: data.defaultPaidBy ?? null,
                defaultFundId: data.defaultFundId ?? null,
                defaultFundPaymentMode: data.defaultFundPaymentMode ?? null,
                ...audit,
            })
            .where(eq(expenseTemplates.id, existing.templateId)),
        client
            .update(recurringExpenses)
            .set({
                name: data.name,
                // Reset override so the edited template amount is the effective amount.
                amountOverride: null,
                scheduleUnit: data.scheduleUnit,
                scheduleInterval: data.scheduleInterval,
                anchorDate: data.anchorDate,
                generationMode: data.generationMode,
                endDate: data.endDate ?? null,
                endAfterCount: data.endAfterCount ?? null,
                nextOccurrenceAt,
                ...audit,
            })
            .where(eq(recurringExpenses.id, data.id)),
    ];

    await client.batch(batchOps as [typeof batchOps[0], ...typeof batchOps]);

    // Optional: propagate edits to every past expense generated by this rule.
    let appliedToPast = 0;
    if (data.applyToPast) {
        const resolvedPaidBy =
            data.defaultPaidBy === '__creator__'
                ? existing.createdBy
                : data.defaultPaidBy ?? null;

        const generated = await client
            .select()
            .from(expenses)
            .where(
                and(
                    eq(expenses.recurringExpenseId, data.id),
                    isNull(expenses.deletedAt),
                ),
            );

        const newFundId = data.defaultFundId ?? null;
        const newFundMode =
            (data.defaultFundPaymentMode as 'paid_by_fund' | 'pending_reimbursement' | null) ??
            null;
        const newAmount = data.defaultAmount;

        for (const exp of generated) {
            try {
                const oldFundId = exp.fundId;
                const oldFundMode = exp.fundPaymentMode;
                const oldAmount = exp.amount;
                const oldFundTxId = exp.fundTransactionId;

                let finalFundTxId: string | null = oldFundTxId;

                // Fund re-wiring decision tree
                const fundSame = oldFundId === newFundId && oldFundMode === newFundMode;
                if (fundSame) {
                    // Same fund + mode. Only amount delta may need applying.
                    if (oldFundTxId && newAmount !== oldAmount) {
                        await applyFundAmountDelta(oldFundTxId, oldAmount, newAmount, userId, env);
                    }
                } else {
                    // Fund or mode changed. Detach old, attach new.
                    if (oldFundTxId) {
                        await detachFundFromExpense(oldFundTxId, oldFundMode, userId, env);
                    }
                    if (newFundId && newFundMode) {
                        finalFundTxId = await attachFundToExpense(
                            exp.id,
                            data.vaultId,
                            newFundId,
                            newFundMode,
                            newAmount,
                            userId,
                            env,
                        );
                    } else {
                        finalFundTxId = null;
                    }
                }

                await client
                    .update(expenses)
                    .set({
                        amount: newAmount,
                        categoryName: data.defaultCategoryName,
                        note: data.defaultNote ?? null,
                        paymentType: data.defaultPaymentType ?? 'cash',
                        paidBy: resolvedPaidBy,
                        fundId: newFundId,
                        fundPaymentMode: newFundMode,
                        fundTransactionId: finalFundTxId,
                        ...updateAuditFields({ userId }),
                    })
                    .where(eq(expenses.id, exp.id));

                appliedToPast++;
            } catch (error) {
                console.error({
                    message: 'Failed to apply edit to past expense',
                    expenseId: exp.id,
                    error,
                });
                // Continue — partial propagation is better than nothing.
            }
        }
    }

    return {
        ruleId: data.id,
        templateId: existing.templateId,
        appliedToPast,
    };
};
