import type { IconItem } from '$lib/components/ui/icon-combobox';

export const iconData: { icons: IconItem[] } = {
	icons: [
		// Money & Finance
		{ icon: '💰', name: 'Money Bag', keywords: ['money', 'cash', 'dollar', 'wealth'], group: 'Money & Finance' },
		{ icon: '💵', name: 'Dollar Bill', keywords: ['money', 'cash', 'dollar', 'currency'], group: 'Money & Finance' },
		{ icon: '💴', name: 'Yen Bill', keywords: ['yen', 'currency', 'japan', 'money'], group: 'Money & Finance' },
		{ icon: '💶', name: 'Euro Bill', keywords: ['euro', 'currency', 'europe', 'money'], group: 'Money & Finance' },
		{ icon: '💷', name: 'Pound Bill', keywords: ['pound', 'currency', 'uk', 'money'], group: 'Money & Finance' },
		{ icon: '💸', name: 'Money with Wings', keywords: ['money', 'spending', 'expense', 'flying'], group: 'Money & Finance' },
		{ icon: '🪙', name: 'Coin', keywords: ['money', 'currency', 'coin', 'gold'], group: 'Money & Finance' },
		{ icon: '💳', name: 'Credit Card', keywords: ['card', 'payment', 'credit', 'debit'], group: 'Money & Finance' },
		{ icon: '💎', name: 'Gem Stone', keywords: ['diamond', 'jewel', 'valuable', 'expensive'], group: 'Money & Finance' },
		{ icon: '🏦', name: 'Bank', keywords: ['bank', 'building', 'finance', 'money'], group: 'Money & Finance' },
		{ icon: '🏧', name: 'ATM', keywords: ['atm', 'cash', 'machine', 'bank'], group: 'Money & Finance' },
		{ icon: '💹', name: 'Chart Increasing Yen', keywords: ['chart', 'graph', 'stock', 'finance'], group: 'Money & Finance' },
		{ icon: '💱', name: 'Currency Exchange', keywords: ['exchange', 'currency', 'forex', 'money'], group: 'Money & Finance' },
		{ icon: '💲', name: 'Dollar Sign', keywords: ['dollar', 'money', 'currency', 'price'], group: 'Money & Finance' },
		{ icon: '🤑', name: 'Money-Mouth Face', keywords: ['money', 'rich', 'greedy', 'wealthy'], group: 'Money & Finance' },
		{ icon: '💼', name: 'Briefcase', keywords: ['briefcase', 'business', 'work', 'finance'], group: 'Money & Finance' },
		{ icon: '📊', name: 'Bar Chart', keywords: ['chart', 'graph', 'statistics', 'finance'], group: 'Money & Finance' },
		{ icon: '📈', name: 'Chart Increasing', keywords: ['chart', 'growth', 'profit', 'increase'], group: 'Money & Finance' },
		{ icon: '📉', name: 'Chart Decreasing', keywords: ['chart', 'decline', 'loss', 'decrease'], group: 'Money & Finance' },
		{ icon: '🧾', name: 'Receipt', keywords: ['receipt', 'bill', 'invoice', 'payment'], group: 'Money & Finance' },
		{ icon: '💰', name: 'Money Bag', keywords: ['savings', 'wealth', 'treasure', 'income'], group: 'Money & Finance' },
		{ icon: '🏅', name: 'Medal', keywords: ['medal', 'award', 'achievement', 'bonus'], group: 'Money & Finance' },
		{ icon: '🎖️', name: 'Military Medal', keywords: ['medal', 'award', 'honor', 'achievement'], group: 'Money & Finance' },
		{ icon: '💵', name: 'Banknote', keywords: ['cash', 'bill', 'payment', 'money'], group: 'Money & Finance' },
		{ icon: '🪪', name: 'ID Card', keywords: ['id', 'identification', 'card', 'license'], group: 'Money & Finance' },

		// Buildings & Places
		{ icon: '🏠', name: 'House', keywords: ['home', 'house', 'building', 'rent'], group: 'Buildings & Places' },
		{ icon: '🏢', name: 'Office Building', keywords: ['office', 'work', 'building', 'business'], group: 'Buildings & Places' },
		{ icon: '🏪', name: 'Store', keywords: ['shop', 'store', 'shopping', 'retail'], group: 'Buildings & Places' },
		{ icon: '🏫', name: 'School', keywords: ['school', 'education', 'learning', 'building'], group: 'Buildings & Places' },
		{ icon: '🏥', name: 'Hospital', keywords: ['hospital', 'health', 'medical', 'doctor'], group: 'Buildings & Places' },
		{ icon: '🏨', name: 'Hotel', keywords: ['hotel', 'accommodation', 'lodging', 'travel'], group: 'Buildings & Places' },
		{ icon: '🏛️', name: 'Classical Building', keywords: ['museum', 'government', 'monument', 'building'], group: 'Buildings & Places' },
		{ icon: '⛪', name: 'Church', keywords: ['church', 'religion', 'building', 'worship'], group: 'Buildings & Places' },
		{ icon: '🕌', name: 'Mosque', keywords: ['mosque', 'religion', 'islam', 'worship'], group: 'Buildings & Places' },

		// Transportation & Vehicles
		{ icon: '🚗', name: 'Car', keywords: ['car', 'vehicle', 'auto', 'transport'], group: 'Transportation & Vehicles' },
		{ icon: '🚕', name: 'Taxi', keywords: ['taxi', 'cab', 'transport', 'ride'], group: 'Transportation & Vehicles' },
		{ icon: '🚙', name: 'SUV', keywords: ['suv', 'car', 'vehicle', 'auto'], group: 'Transportation & Vehicles' },
		{ icon: '🚌', name: 'Bus', keywords: ['bus', 'transport', 'public', 'travel'], group: 'Transportation & Vehicles' },
		{ icon: '🚎', name: 'Trolleybus', keywords: ['bus', 'trolley', 'transport', 'public'], group: 'Transportation & Vehicles' },
		{ icon: '🚐', name: 'Minibus', keywords: ['minibus', 'van', 'transport', 'vehicle'], group: 'Transportation & Vehicles' },
		{ icon: '🚑', name: 'Ambulance', keywords: ['ambulance', 'emergency', 'medical', 'hospital'], group: 'Transportation & Vehicles' },
		{ icon: '🚒', name: 'Fire Engine', keywords: ['fire', 'truck', 'emergency', 'rescue'], group: 'Transportation & Vehicles' },
		{ icon: '🚓', name: 'Police Car', keywords: ['police', 'cop', 'law', 'emergency'], group: 'Transportation & Vehicles' },
		{ icon: '🚚', name: 'Delivery Truck', keywords: ['truck', 'delivery', 'transport', 'cargo'], group: 'Transportation & Vehicles' },
		{ icon: '🚛', name: 'Semi Truck', keywords: ['truck', 'semi', 'trailer', 'transport'], group: 'Transportation & Vehicles' },
		{ icon: '🏎️', name: 'Race Car', keywords: ['race', 'car', 'fast', 'sports car'], group: 'Transportation & Vehicles' },
		{ icon: '🛻', name: 'Pickup Truck', keywords: ['pickup', 'truck', 'vehicle', 'utility'], group: 'Transportation & Vehicles' },
		{ icon: '🚘', name: 'Oncoming Car', keywords: ['car', 'vehicle', 'auto', 'oncoming'], group: 'Transportation & Vehicles' },
		{ icon: '🚖', name: 'Oncoming Taxi', keywords: ['taxi', 'cab', 'oncoming', 'vehicle'], group: 'Transportation & Vehicles' },
		{ icon: '🚲', name: 'Bicycle', keywords: ['bike', 'bicycle', 'cycling', 'transport'], group: 'Transportation & Vehicles' },
		{ icon: '🛵', name: 'Motor Scooter', keywords: ['scooter', 'motorcycle', 'moped', 'bike'], group: 'Transportation & Vehicles' },
		{ icon: '🏍️', name: 'Motorcycle', keywords: ['motorcycle', 'bike', 'motor', 'transport'], group: 'Transportation & Vehicles' },
		{ icon: '🛺', name: 'Auto Rickshaw', keywords: ['rickshaw', 'tuk tuk', 'vehicle', 'transport'], group: 'Transportation & Vehicles' },
		{ icon: '✈️', name: 'Airplane', keywords: ['airplane', 'plane', 'flight', 'travel'], group: 'Transportation & Vehicles' },
		{ icon: '🚁', name: 'Helicopter', keywords: ['helicopter', 'chopper', 'flight', 'aircraft'], group: 'Transportation & Vehicles' },
		{ icon: '🛩️', name: 'Small Airplane', keywords: ['airplane', 'small', 'plane', 'flight'], group: 'Transportation & Vehicles' },
		{ icon: '🚂', name: 'Train', keywords: ['train', 'railway', 'transport', 'locomotive'], group: 'Transportation & Vehicles' },
		{ icon: '🚇', name: 'Metro', keywords: ['metro', 'subway', 'underground', 'train'], group: 'Transportation & Vehicles' },
		{ icon: '🚆', name: 'Train', keywords: ['train', 'railway', 'commute', 'transport'], group: 'Transportation & Vehicles' },
		{ icon: '🚊', name: 'Tram', keywords: ['tram', 'streetcar', 'trolley', 'transport'], group: 'Transportation & Vehicles' },
		{ icon: '🚝', name: 'Monorail', keywords: ['monorail', 'train', 'railway', 'transport'], group: 'Transportation & Vehicles' },
		{ icon: '🚄', name: 'High-Speed Train', keywords: ['train', 'bullet', 'fast', 'railway'], group: 'Transportation & Vehicles' },
		{ icon: '🚅', name: 'Bullet Train', keywords: ['train', 'bullet', 'shinkansen', 'fast'], group: 'Transportation & Vehicles' },
		{ icon: '🚢', name: 'Ship', keywords: ['ship', 'boat', 'cruise', 'ocean'], group: 'Transportation & Vehicles' },
		{ icon: '⛴️', name: 'Ferry', keywords: ['ferry', 'boat', 'water', 'transport'], group: 'Transportation & Vehicles' },
		{ icon: '🚤', name: 'Speedboat', keywords: ['boat', 'speedboat', 'water', 'fast'], group: 'Transportation & Vehicles' },
		{ icon: '🛥️', name: 'Motor Boat', keywords: ['boat', 'motor', 'water', 'yacht'], group: 'Transportation & Vehicles' },
		{ icon: '⛵', name: 'Sailboat', keywords: ['sailboat', 'boat', 'sailing', 'yacht'], group: 'Transportation & Vehicles' },
		{ icon: '🛳️', name: 'Cruise Ship', keywords: ['cruise', 'ship', 'passenger', 'ocean'], group: 'Transportation & Vehicles' },
		{ icon: '🚟', name: 'Suspension Railway', keywords: ['railway', 'suspension', 'transport', 'monorail'], group: 'Transportation & Vehicles' },
		{ icon: '🚠', name: 'Cable Car', keywords: ['cable car', 'mountain', 'gondola', 'transport'], group: 'Transportation & Vehicles' },
		{ icon: '🚡', name: 'Aerial Tramway', keywords: ['tramway', 'aerial', 'cable', 'mountain'], group: 'Transportation & Vehicles' },
		{ icon: '🛰️', name: 'Satellite', keywords: ['satellite', 'space', 'orbit', 'communication'], group: 'Transportation & Vehicles' },
		{ icon: '🚀', name: 'Rocket', keywords: ['rocket', 'space', 'launch', 'spacecraft'], group: 'Transportation & Vehicles' },
		{ icon: '⛽', name: 'Fuel Pump', keywords: ['fuel', 'gas', 'petrol', 'station'], group: 'Transportation & Vehicles' },
		{ icon: '🅿️', name: 'Parking', keywords: ['parking', 'park', 'car', 'lot'], group: 'Transportation & Vehicles' },

		// Food & Dining
		{ icon: '🍔', name: 'Hamburger', keywords: ['burger', 'food', 'fast food', 'meal'], group: 'Food & Dining' },
		{ icon: '🍕', name: 'Pizza', keywords: ['pizza', 'food', 'italian', 'meal'], group: 'Food & Dining' },
		{ icon: '🍟', name: 'Fries', keywords: ['fries', 'french fries', 'food', 'fast food'], group: 'Food & Dining' },
		{ icon: '🌭', name: 'Hot Dog', keywords: ['hot dog', 'food', 'sausage', 'fast food'], group: 'Food & Dining' },
		{ icon: '🥗', name: 'Salad', keywords: ['salad', 'healthy', 'vegetables', 'food'], group: 'Food & Dining' },
		{ icon: '🍝', name: 'Pasta', keywords: ['pasta', 'spaghetti', 'italian', 'food'], group: 'Food & Dining' },
		{ icon: '🍜', name: 'Noodles', keywords: ['noodles', 'ramen', 'soup', 'asian'], group: 'Food & Dining' },
		{ icon: '🍱', name: 'Bento Box', keywords: ['bento', 'lunch', 'japanese', 'food'], group: 'Food & Dining' },
		{ icon: '🍛', name: 'Curry', keywords: ['curry', 'rice', 'indian', 'food'], group: 'Food & Dining' },
		{ icon: '🍲', name: 'Stew', keywords: ['stew', 'pot', 'soup', 'food'], group: 'Food & Dining' },
		{ icon: '🥘', name: 'Paella', keywords: ['paella', 'rice', 'spanish', 'food'], group: 'Food & Dining' },
		{ icon: '🍣', name: 'Sushi', keywords: ['sushi', 'japanese', 'fish', 'food'], group: 'Food & Dining' },
		{ icon: '🍱', name: 'Lunch Box', keywords: ['lunch', 'box', 'meal', 'food'], group: 'Food & Dining' },
		{ icon: '🥪', name: 'Sandwich', keywords: ['sandwich', 'bread', 'meal', 'food'], group: 'Food & Dining' },
		{ icon: '🌮', name: 'Taco', keywords: ['taco', 'mexican', 'food', 'meal'], group: 'Food & Dining' },
		{ icon: '🌯', name: 'Burrito', keywords: ['burrito', 'mexican', 'wrap', 'food'], group: 'Food & Dining' },
		{ icon: '🥙', name: 'Kebab', keywords: ['kebab', 'pita', 'middle eastern', 'food'], group: 'Food & Dining' },
		{ icon: '🧆', name: 'Falafel', keywords: ['falafel', 'chickpea', 'middle eastern', 'food'], group: 'Food & Dining' },
		{ icon: '🥚', name: 'Egg', keywords: ['egg', 'breakfast', 'protein', 'food'], group: 'Food & Dining' },
		{ icon: '🍳', name: 'Fried Egg', keywords: ['egg', 'fried', 'breakfast', 'food'], group: 'Food & Dining' },
		{ icon: '🥞', name: 'Pancakes', keywords: ['pancakes', 'breakfast', 'sweet', 'food'], group: 'Food & Dining' },
		{ icon: '🧇', name: 'Waffle', keywords: ['waffle', 'breakfast', 'sweet', 'food'], group: 'Food & Dining' },
		{ icon: '🥓', name: 'Bacon', keywords: ['bacon', 'breakfast', 'meat', 'food'], group: 'Food & Dining' },
		{ icon: '🥩', name: 'Steak', keywords: ['steak', 'meat', 'beef', 'food'], group: 'Food & Dining' },
		{ icon: '🍖', name: 'Meat on Bone', keywords: ['meat', 'bone', 'food', 'protein'], group: 'Food & Dining' },
		{ icon: '🍗', name: 'Chicken Leg', keywords: ['chicken', 'poultry', 'drumstick', 'food'], group: 'Food & Dining' },
		{ icon: '🍤', name: 'Fried Shrimp', keywords: ['shrimp', 'seafood', 'fried', 'food'], group: 'Food & Dining' },
		{ icon: '🦐', name: 'Shrimp', keywords: ['shrimp', 'seafood', 'prawn', 'food'], group: 'Food & Dining' },
		{ icon: '🦞', name: 'Lobster', keywords: ['lobster', 'seafood', 'shellfish', 'food'], group: 'Food & Dining' },
		{ icon: '🦀', name: 'Crab', keywords: ['crab', 'seafood', 'shellfish', 'food'], group: 'Food & Dining' },
		{ icon: '🐟', name: 'Fish', keywords: ['fish', 'seafood', 'food', 'protein'], group: 'Food & Dining' },
		{ icon: '🐠', name: 'Tropical Fish', keywords: ['fish', 'tropical', 'seafood', 'food'], group: 'Food & Dining' },
		{ icon: '🍙', name: 'Rice Ball', keywords: ['rice', 'onigiri', 'japanese', 'food'], group: 'Food & Dining' },
		{ icon: '🍚', name: 'Cooked Rice', keywords: ['rice', 'food', 'grain', 'asian'], group: 'Food & Dining' },
		{ icon: '🍥', name: 'Fish Cake', keywords: ['fish cake', 'japanese', 'food', 'narutomaki'], group: 'Food & Dining' },
		{ icon: '🥟', name: 'Dumpling', keywords: ['dumpling', 'gyoza', 'asian', 'food'], group: 'Food & Dining' },
		{ icon: '🍢', name: 'Oden', keywords: ['oden', 'skewer', 'japanese', 'food'], group: 'Food & Dining' },
		{ icon: '🍡', name: 'Dango', keywords: ['dango', 'sweet', 'japanese', 'dessert'], group: 'Food & Dining' },
		{ icon: '🥠', name: 'Fortune Cookie', keywords: ['fortune', 'cookie', 'chinese', 'dessert'], group: 'Food & Dining' },
		{ icon: '🥡', name: 'Takeout Box', keywords: ['takeout', 'chinese', 'food', 'delivery'], group: 'Food & Dining' },
		{ icon: '🍞', name: 'Bread', keywords: ['bread', 'loaf', 'bakery', 'food'], group: 'Food & Dining' },
		{ icon: '🥐', name: 'Croissant', keywords: ['croissant', 'pastry', 'french', 'breakfast'], group: 'Food & Dining' },
		{ icon: '🥖', name: 'Baguette', keywords: ['baguette', 'bread', 'french', 'bakery'], group: 'Food & Dining' },
		{ icon: '🥨', name: 'Pretzel', keywords: ['pretzel', 'snack', 'bread', 'german'], group: 'Food & Dining' },
		{ icon: '🥯', name: 'Bagel', keywords: ['bagel', 'bread', 'breakfast', 'food'], group: 'Food & Dining' },
		{ icon: '🧀', name: 'Cheese', keywords: ['cheese', 'dairy', 'food', 'wedge'], group: 'Food & Dining' },
		{ icon: '🍕', name: 'Pizza Slice', keywords: ['pizza', 'slice', 'italian', 'food'], group: 'Food & Dining' },
		{ icon: '🥫', name: 'Canned Food', keywords: ['can', 'canned', 'food', 'preserved'], group: 'Food & Dining' },
		{ icon: '🍿', name: 'Popcorn', keywords: ['popcorn', 'snack', 'cinema', 'food'], group: 'Food & Dining' },
		{ icon: '🧈', name: 'Butter', keywords: ['butter', 'dairy', 'spread', 'food'], group: 'Food & Dining' },
		{ icon: '🧂', name: 'Salt', keywords: ['salt', 'seasoning', 'condiment', 'food'], group: 'Food & Dining' },
		{ icon: '🍅', name: 'Tomato', keywords: ['tomato', 'vegetable', 'food', 'fresh'], group: 'Food & Dining' },
		{ icon: '🥑', name: 'Avocado', keywords: ['avocado', 'fruit', 'healthy', 'food'], group: 'Food & Dining' },
		{ icon: '🥦', name: 'Broccoli', keywords: ['broccoli', 'vegetable', 'healthy', 'green'], group: 'Food & Dining' },
		{ icon: '🥒', name: 'Cucumber', keywords: ['cucumber', 'vegetable', 'salad', 'food'], group: 'Food & Dining' },
		{ icon: '🌶️', name: 'Hot Pepper', keywords: ['pepper', 'chili', 'spicy', 'hot'], group: 'Food & Dining' },
		{ icon: '🫑', name: 'Bell Pepper', keywords: ['pepper', 'bell', 'vegetable', 'food'], group: 'Food & Dining' },
		{ icon: '🌽', name: 'Corn', keywords: ['corn', 'vegetable', 'maize', 'food'], group: 'Food & Dining' },
		{ icon: '🥕', name: 'Carrot', keywords: ['carrot', 'vegetable', 'orange', 'food'], group: 'Food & Dining' },
		{ icon: '🥔', name: 'Potato', keywords: ['potato', 'vegetable', 'food', 'starch'], group: 'Food & Dining' },
		{ icon: '🍠', name: 'Sweet Potato', keywords: ['sweet potato', 'yam', 'vegetable', 'food'], group: 'Food & Dining' },
		{ icon: '🥜', name: 'Peanuts', keywords: ['peanuts', 'nuts', 'snack', 'protein'], group: 'Food & Dining' },
		{ icon: '🍯', name: 'Honey', keywords: ['honey', 'sweet', 'bee', 'natural'], group: 'Food & Dining' },
		{ icon: '🍎', name: 'Red Apple', keywords: ['apple', 'fruit', 'healthy', 'red'], group: 'Food & Dining' },
		{ icon: '🍏', name: 'Green Apple', keywords: ['apple', 'fruit', 'healthy', 'green'], group: 'Food & Dining' },
		{ icon: '🍊', name: 'Orange', keywords: ['orange', 'fruit', 'citrus', 'vitamin'], group: 'Food & Dining' },
		{ icon: '🍋', name: 'Lemon', keywords: ['lemon', 'fruit', 'citrus', 'sour'], group: 'Food & Dining' },
		{ icon: '🍌', name: 'Banana', keywords: ['banana', 'fruit', 'yellow', 'potassium'], group: 'Food & Dining' },
		{ icon: '🍉', name: 'Watermelon', keywords: ['watermelon', 'fruit', 'summer', 'refreshing'], group: 'Food & Dining' },
		{ icon: '🍇', name: 'Grapes', keywords: ['grapes', 'fruit', 'wine', 'bunch'], group: 'Food & Dining' },
		{ icon: '🍓', name: 'Strawberry', keywords: ['strawberry', 'fruit', 'berry', 'sweet'], group: 'Food & Dining' },
		{ icon: '🫐', name: 'Blueberries', keywords: ['blueberries', 'fruit', 'berry', 'healthy'], group: 'Food & Dining' },
		{ icon: '🍈', name: 'Melon', keywords: ['melon', 'fruit', 'cantaloupe', 'sweet'], group: 'Food & Dining' },
		{ icon: '🍒', name: 'Cherries', keywords: ['cherries', 'fruit', 'red', 'sweet'], group: 'Food & Dining' },
		{ icon: '🍑', name: 'Peach', keywords: ['peach', 'fruit', 'sweet', 'juicy'], group: 'Food & Dining' },
		{ icon: '🥭', name: 'Mango', keywords: ['mango', 'fruit', 'tropical', 'sweet'], group: 'Food & Dining' },
		{ icon: '🍍', name: 'Pineapple', keywords: ['pineapple', 'fruit', 'tropical', 'sweet'], group: 'Food & Dining' },
		{ icon: '🥥', name: 'Coconut', keywords: ['coconut', 'fruit', 'tropical', 'nut'], group: 'Food & Dining' },
		{ icon: '🥝', name: 'Kiwi', keywords: ['kiwi', 'fruit', 'green', 'vitamin'], group: 'Food & Dining' },
		{ icon: '☕', name: 'Coffee', keywords: ['coffee', 'cafe', 'drink', 'hot'], group: 'Food & Dining' },
		{ icon: '🍵', name: 'Tea', keywords: ['tea', 'drink', 'hot', 'green'], group: 'Food & Dining' },
		{ icon: '🧃', name: 'Juice Box', keywords: ['juice', 'drink', 'box', 'kid'], group: 'Food & Dining' },
		{ icon: '🥤', name: 'Cup with Straw', keywords: ['drink', 'soda', 'cup', 'straw'], group: 'Food & Dining' },
		{ icon: '🧋', name: 'Bubble Tea', keywords: ['bubble tea', 'boba', 'drink', 'asian'], group: 'Food & Dining' },
		{ icon: '🧉', name: 'Mate', keywords: ['mate', 'tea', 'drink', 'south american'], group: 'Food & Dining' },
		{ icon: '🍶', name: 'Sake', keywords: ['sake', 'japanese', 'drink', 'alcohol'], group: 'Food & Dining' },
		{ icon: '🍺', name: 'Beer Mug', keywords: ['beer', 'drink', 'alcohol', 'mug'], group: 'Food & Dining' },
		{ icon: '🍻', name: 'Clinking Beer Mugs', keywords: ['beer', 'cheers', 'drink', 'celebration'], group: 'Food & Dining' },
		{ icon: '🍷', name: 'Wine Glass', keywords: ['wine', 'drink', 'alcohol', 'glass'], group: 'Food & Dining' },
		{ icon: '🥂', name: 'Clinking Glasses', keywords: ['champagne', 'cheers', 'celebration', 'toast'], group: 'Food & Dining' },
		{ icon: '🍸', name: 'Cocktail', keywords: ['cocktail', 'drink', 'alcohol', 'martini'], group: 'Food & Dining' },
		{ icon: '🍹', name: 'Tropical Drink', keywords: ['tropical', 'cocktail', 'drink', 'vacation'], group: 'Food & Dining' },
		{ icon: '🧊', name: 'Ice Cube', keywords: ['ice', 'cold', 'frozen', 'drink'], group: 'Food & Dining' },
		{ icon: '🍰', name: 'Shortcake', keywords: ['cake', 'dessert', 'sweet', 'birthday'], group: 'Food & Dining' },
		{ icon: '🎂', name: 'Birthday Cake', keywords: ['birthday', 'cake', 'celebration', 'candles'], group: 'Food & Dining' },
		{ icon: '🧁', name: 'Cupcake', keywords: ['cupcake', 'dessert', 'sweet', 'bakery'], group: 'Food & Dining' },
		{ icon: '🥧', name: 'Pie', keywords: ['pie', 'dessert', 'bakery', 'sweet'], group: 'Food & Dining' },
		{ icon: '🍮', name: 'Custard', keywords: ['custard', 'pudding', 'dessert', 'sweet'], group: 'Food & Dining' },
		{ icon: '🍭', name: 'Lollipop', keywords: ['lollipop', 'candy', 'sweet', 'sugar'], group: 'Food & Dining' },
		{ icon: '🍬', name: 'Candy', keywords: ['candy', 'sweet', 'sugar', 'treat'], group: 'Food & Dining' },
		{ icon: '🍫', name: 'Chocolate', keywords: ['chocolate', 'candy', 'sweet', 'dessert'], group: 'Food & Dining' },
		{ icon: '🍿', name: 'Popcorn', keywords: ['popcorn', 'snack', 'movie', 'cinema'], group: 'Food & Dining' },
		{ icon: '🍩', name: 'Doughnut', keywords: ['donut', 'doughnut', 'dessert', 'sweet'], group: 'Food & Dining' },
		{ icon: '🍪', name: 'Cookie', keywords: ['cookie', 'dessert', 'sweet', 'snack'], group: 'Food & Dining' },
		{ icon: '🌰', name: 'Chestnut', keywords: ['chestnut', 'nut', 'autumn', 'food'], group: 'Food & Dining' },
		{ icon: '🍦', name: 'Soft Ice Cream', keywords: ['ice cream', 'dessert', 'sweet', 'frozen'], group: 'Food & Dining' },
		{ icon: '🍨', name: 'Ice Cream', keywords: ['ice cream', 'dessert', 'sweet', 'frozen'], group: 'Food & Dining' },
		{ icon: '🍧', name: 'Shaved Ice', keywords: ['shaved ice', 'dessert', 'frozen', 'sweet'], group: 'Food & Dining' },
		{ icon: '🥮', name: 'Mooncake', keywords: ['mooncake', 'chinese', 'dessert', 'sweet'], group: 'Food & Dining' },
		{ icon: '🍡', name: 'Dango', keywords: ['dango', 'japanese', 'dessert', 'sweet'], group: 'Food & Dining' },

		// Meals & Dining Times
		{ icon: '🌅', name: 'Sunrise', keywords: ['sunrise', 'morning', 'breakfast', 'dawn'], group: 'Meals & Dining Times' },
		{ icon: '🌄', name: 'Sunrise Over Mountains', keywords: ['sunrise', 'morning', 'breakfast', 'early'], group: 'Meals & Dining Times' },
		{ icon: '🍳', name: 'Breakfast - Fried Egg', keywords: ['breakfast', 'egg', 'morning', 'fried'], group: 'Meals & Dining Times' },
		{ icon: '🥞', name: 'Breakfast - Pancakes', keywords: ['breakfast', 'pancakes', 'morning', 'sweet'], group: 'Meals & Dining Times' },
		{ icon: '🧇', name: 'Breakfast - Waffle', keywords: ['breakfast', 'waffle', 'morning', 'sweet'], group: 'Meals & Dining Times' },
		{ icon: '🥓', name: 'Breakfast - Bacon', keywords: ['breakfast', 'bacon', 'morning', 'meat'], group: 'Meals & Dining Times' },
		{ icon: '🍞', name: 'Breakfast - Bread', keywords: ['breakfast', 'bread', 'toast', 'morning'], group: 'Meals & Dining Times' },
		{ icon: '🥐', name: 'Breakfast - Croissant', keywords: ['breakfast', 'croissant', 'morning', 'french'], group: 'Meals & Dining Times' },
		{ icon: '🥯', name: 'Breakfast - Bagel', keywords: ['breakfast', 'bagel', 'morning', 'bread'], group: 'Meals & Dining Times' },
		{ icon: '🥣', name: 'Breakfast - Cereal', keywords: ['breakfast', 'cereal', 'morning', 'bowl'], group: 'Meals & Dining Times' },
		{ icon: '🥛', name: 'Breakfast - Milk', keywords: ['breakfast', 'milk', 'morning', 'drink'], group: 'Meals & Dining Times' },
		{ icon: '☕', name: 'Breakfast - Coffee', keywords: ['breakfast', 'coffee', 'morning', 'caffeine'], group: 'Meals & Dining Times' },
		{ icon: '🧃', name: 'Breakfast - Juice', keywords: ['breakfast', 'juice', 'morning', 'orange juice'], group: 'Meals & Dining Times' },
		{ icon: '🥤', name: 'Breakfast - Smoothie', keywords: ['breakfast', 'smoothie', 'morning', 'healthy'], group: 'Meals & Dining Times' },
		{ icon: '🍊', name: 'Breakfast - Orange', keywords: ['breakfast', 'orange', 'morning', 'fruit'], group: 'Meals & Dining Times' },
		{ icon: '🍌', name: 'Breakfast - Banana', keywords: ['breakfast', 'banana', 'morning', 'fruit'], group: 'Meals & Dining Times' },
		{ icon: '🥚', name: 'Breakfast - Egg', keywords: ['breakfast', 'egg', 'morning', 'protein'], group: 'Meals & Dining Times' },
		{ icon: '🧈', name: 'Breakfast - Butter', keywords: ['breakfast', 'butter', 'morning', 'spread'], group: 'Meals & Dining Times' },
		{ icon: '🍯', name: 'Breakfast - Honey', keywords: ['breakfast', 'honey', 'morning', 'sweet'], group: 'Meals & Dining Times' },
		{ icon: '🌞', name: 'Brunch - Sunny Day', keywords: ['brunch', 'late morning', 'meal', 'weekend'], group: 'Meals & Dining Times' },
		{ icon: '🥂', name: 'Brunch - Mimosa', keywords: ['brunch', 'champagne', 'drink', 'celebration'], group: 'Meals & Dining Times' },
		{ icon: '🥗', name: 'Brunch - Salad', keywords: ['brunch', 'salad', 'healthy', 'lunch'], group: 'Meals & Dining Times' },
		{ icon: '🍳', name: 'Brunch - Eggs Benedict', keywords: ['brunch', 'eggs', 'benedict', 'classic'], group: 'Meals & Dining Times' },
		{ icon: '🌮', name: 'Brunch - Breakfast Taco', keywords: ['brunch', 'taco', 'mexican', 'breakfast'], group: 'Meals & Dining Times' },
		{ icon: '🌯', name: 'Brunch - Breakfast Burrito', keywords: ['brunch', 'burrito', 'mexican', 'wrap'], group: 'Meals & Dining Times' },
		{ icon: '🥪', name: 'Brunch - Sandwich', keywords: ['brunch', 'sandwich', 'meal', 'lunch'], group: 'Meals & Dining Times' },
		{ icon: '🌤️', name: 'Lunch - Midday', keywords: ['lunch', 'midday', 'afternoon', 'meal'], group: 'Meals & Dining Times' },
		{ icon: '☀️', name: 'Lunch - Daytime', keywords: ['lunch', 'day', 'noon', 'meal'], group: 'Meals & Dining Times' },
		{ icon: '🍱', name: 'Lunch - Bento Box', keywords: ['lunch', 'bento', 'japanese', 'meal'], group: 'Meals & Dining Times' },
		{ icon: '🥗', name: 'Lunch - Salad', keywords: ['lunch', 'salad', 'healthy', 'light'], group: 'Meals & Dining Times' },
		{ icon: '🥪', name: 'Lunch - Sandwich', keywords: ['lunch', 'sandwich', 'bread', 'meal'], group: 'Meals & Dining Times' },
		{ icon: '🍜', name: 'Lunch - Noodles', keywords: ['lunch', 'noodles', 'ramen', 'asian'], group: 'Meals & Dining Times' },
		{ icon: '🍝', name: 'Lunch - Pasta', keywords: ['lunch', 'pasta', 'italian', 'spaghetti'], group: 'Meals & Dining Times' },
		{ icon: '🍛', name: 'Lunch - Curry', keywords: ['lunch', 'curry', 'rice', 'spicy'], group: 'Meals & Dining Times' },
		{ icon: '🍲', name: 'Lunch - Stew', keywords: ['lunch', 'stew', 'soup', 'hot'], group: 'Meals & Dining Times' },
		{ icon: '🍕', name: 'Lunch - Pizza', keywords: ['lunch', 'pizza', 'italian', 'slice'], group: 'Meals & Dining Times' },
		{ icon: '🍔', name: 'Lunch - Burger', keywords: ['lunch', 'burger', 'fast food', 'meal'], group: 'Meals & Dining Times' },
		{ icon: '🌮', name: 'Lunch - Taco', keywords: ['lunch', 'taco', 'mexican', 'meal'], group: 'Meals & Dining Times' },
		{ icon: '🌯', name: 'Lunch - Burrito', keywords: ['lunch', 'burrito', 'mexican', 'wrap'], group: 'Meals & Dining Times' },
		{ icon: '🥙', name: 'Lunch - Wrap', keywords: ['lunch', 'wrap', 'pita', 'sandwich'], group: 'Meals & Dining Times' },
		{ icon: '🍙', name: 'Lunch - Rice Ball', keywords: ['lunch', 'onigiri', 'rice', 'japanese'], group: 'Meals & Dining Times' },
		{ icon: '🥡', name: 'Lunch - Takeout', keywords: ['lunch', 'takeout', 'delivery', 'food'], group: 'Meals & Dining Times' },
		{ icon: '☕', name: 'Tea Time - Coffee', keywords: ['tea time', 'coffee', 'break', 'afternoon'], group: 'Meals & Dining Times' },
		{ icon: '🍵', name: 'Tea Time - Tea', keywords: ['tea time', 'tea', 'afternoon', 'break'], group: 'Meals & Dining Times' },
		{ icon: '🫖', name: 'Tea Time - Teapot', keywords: ['tea time', 'teapot', 'tea', 'afternoon'], group: 'Meals & Dining Times' },
		{ icon: '🧋', name: 'Tea Time - Bubble Tea', keywords: ['tea time', 'bubble tea', 'boba', 'drink'], group: 'Meals & Dining Times' },
		{ icon: '🍰', name: 'Tea Time - Cake', keywords: ['tea time', 'cake', 'dessert', 'sweet'], group: 'Meals & Dining Times' },
		{ icon: '🧁', name: 'Tea Time - Cupcake', keywords: ['tea time', 'cupcake', 'dessert', 'sweet'], group: 'Meals & Dining Times' },
		{ icon: '🍪', name: 'Tea Time - Cookies', keywords: ['tea time', 'cookies', 'biscuits', 'snack'], group: 'Meals & Dining Times' },
		{ icon: '🥐', name: 'Tea Time - Pastry', keywords: ['tea time', 'pastry', 'croissant', 'snack'], group: 'Meals & Dining Times' },
		{ icon: '🍩', name: 'Tea Time - Donut', keywords: ['tea time', 'donut', 'snack', 'sweet'], group: 'Meals & Dining Times' },
		{ icon: '🥧', name: 'Tea Time - Pie', keywords: ['tea time', 'pie', 'dessert', 'afternoon'], group: 'Meals & Dining Times' },
		{ icon: '🍫', name: 'Tea Time - Chocolate', keywords: ['tea time', 'chocolate', 'snack', 'sweet'], group: 'Meals & Dining Times' },
		{ icon: '🥤', name: 'Tea Time - Iced Drink', keywords: ['tea time', 'iced', 'drink', 'refreshing'], group: 'Meals & Dining Times' },
		{ icon: '🧃', name: 'Tea Time - Juice', keywords: ['tea time', 'juice', 'drink', 'snack'], group: 'Meals & Dining Times' },
		{ icon: '🌆', name: 'Dinner - Evening', keywords: ['dinner', 'evening', 'sunset', 'night'], group: 'Meals & Dining Times' },
		{ icon: '🌇', name: 'Dinner - Dusk', keywords: ['dinner', 'dusk', 'evening', 'meal'], group: 'Meals & Dining Times' },
		{ icon: '🌃', name: 'Dinner - Night', keywords: ['dinner', 'night', 'evening', 'late'], group: 'Meals & Dining Times' },
		{ icon: '🍽️', name: 'Dinner - Fine Dining', keywords: ['dinner', 'dining', 'restaurant', 'formal'], group: 'Meals & Dining Times' },
		{ icon: '🍴', name: 'Dinner - Utensils', keywords: ['dinner', 'fork', 'knife', 'dining'], group: 'Meals & Dining Times' },
		{ icon: '🥩', name: 'Dinner - Steak', keywords: ['dinner', 'steak', 'meat', 'beef'], group: 'Meals & Dining Times' },
		{ icon: '🍖', name: 'Dinner - Meat', keywords: ['dinner', 'meat', 'bone', 'protein'], group: 'Meals & Dining Times' },
		{ icon: '🍗', name: 'Dinner - Chicken', keywords: ['dinner', 'chicken', 'poultry', 'roast'], group: 'Meals & Dining Times' },
		{ icon: '🐟', name: 'Dinner - Fish', keywords: ['dinner', 'fish', 'seafood', 'healthy'], group: 'Meals & Dining Times' },
		{ icon: '🦞', name: 'Dinner - Lobster', keywords: ['dinner', 'lobster', 'seafood', 'fancy'], group: 'Meals & Dining Times' },
		{ icon: '🍣', name: 'Dinner - Sushi', keywords: ['dinner', 'sushi', 'japanese', 'fish'], group: 'Meals & Dining Times' },
		{ icon: '🍝', name: 'Dinner - Pasta', keywords: ['dinner', 'pasta', 'italian', 'spaghetti'], group: 'Meals & Dining Times' },
		{ icon: '🍕', name: 'Dinner - Pizza', keywords: ['dinner', 'pizza', 'italian', 'casual'], group: 'Meals & Dining Times' },
		{ icon: '🥘', name: 'Dinner - Paella', keywords: ['dinner', 'paella', 'spanish', 'rice'], group: 'Meals & Dining Times' },
		{ icon: '🍲', name: 'Dinner - Hot Pot', keywords: ['dinner', 'hot pot', 'soup', 'stew'], group: 'Meals & Dining Times' },
		{ icon: '🍛', name: 'Dinner - Curry', keywords: ['dinner', 'curry', 'rice', 'spicy'], group: 'Meals & Dining Times' },
		{ icon: '🥗', name: 'Dinner - Salad', keywords: ['dinner', 'salad', 'side', 'healthy'], group: 'Meals & Dining Times' },
		{ icon: '🍷', name: 'Dinner - Wine', keywords: ['dinner', 'wine', 'drink', 'alcohol'], group: 'Meals & Dining Times' },
		{ icon: '🍺', name: 'Dinner - Beer', keywords: ['dinner', 'beer', 'drink', 'casual'], group: 'Meals & Dining Times' },
		{ icon: '🍾', name: 'Dinner - Champagne', keywords: ['dinner', 'champagne', 'celebration', 'fancy'], group: 'Meals & Dining Times' },
		{ icon: '🥂', name: 'Dinner - Toast', keywords: ['dinner', 'toast', 'cheers', 'celebration'], group: 'Meals & Dining Times' },
		{ icon: '🕯️', name: 'Dinner - Candlelight', keywords: ['dinner', 'candle', 'romantic', 'ambiance'], group: 'Meals & Dining Times' },
		{ icon: '🌙', name: 'Late Night - Moon', keywords: ['late night', 'moon', 'midnight', 'snack'], group: 'Meals & Dining Times' },
		{ icon: '🌌', name: 'Late Night - Milky Way', keywords: ['late night', 'night', 'stars', 'midnight'], group: 'Meals & Dining Times' },
		{ icon: '🍕', name: 'Late Night - Pizza', keywords: ['late night', 'pizza', 'snack', 'midnight'], group: 'Meals & Dining Times' },
		{ icon: '🍔', name: 'Late Night - Burger', keywords: ['late night', 'burger', 'snack', 'midnight'], group: 'Meals & Dining Times' },
		{ icon: '🌭', name: 'Late Night - Hot Dog', keywords: ['late night', 'hot dog', 'snack', 'midnight'], group: 'Meals & Dining Times' },
		{ icon: '🍜', name: 'Late Night - Ramen', keywords: ['late night', 'ramen', 'noodles', 'midnight'], group: 'Meals & Dining Times' },
		{ icon: '🍿', name: 'Late Night - Popcorn', keywords: ['late night', 'popcorn', 'snack', 'movie'], group: 'Meals & Dining Times' },
		{ icon: '🍨', name: 'Late Night - Ice Cream', keywords: ['late night', 'ice cream', 'dessert', 'snack'], group: 'Meals & Dining Times' },
		{ icon: '🥤', name: 'Late Night - Soda', keywords: ['late night', 'soda', 'drink', 'snack'], group: 'Meals & Dining Times' },

		// Shopping & Retail
		{ icon: '🛒', name: 'Shopping Cart', keywords: ['cart', 'shopping', 'grocery', 'store'], group: 'Shopping & Retail' },
		{ icon: '🛍️', name: 'Shopping Bags', keywords: ['shopping', 'bags', 'purchase', 'retail'], group: 'Shopping & Retail' },
		{ icon: '🎁', name: 'Gift', keywords: ['gift', 'present', 'wrapped', 'surprise'], group: 'Shopping & Retail' },
		{ icon: '🏷️', name: 'Label', keywords: ['label', 'tag', 'price', 'sale'], group: 'Shopping & Retail' },
		{ icon: '📦', name: 'Package', keywords: ['package', 'box', 'delivery', 'shipping'], group: 'Shopping & Retail' },

		// Store Types
		{ icon: '🏪', name: 'Convenience Store', keywords: ['convenience', '7-11', 'mini mart', 'store', 'shop'], group: 'Shopping & Retail' },
		{ icon: '🏬', name: 'Department Store', keywords: ['department', 'store', 'mall', 'shopping', 'large'], group: 'Shopping & Retail' },
		{ icon: '🏢', name: 'Small Store', keywords: ['small store', 'shop', 'retail', 'business', 'boutique'], group: 'Shopping & Retail' },
		{ icon: '🏘️', name: 'Neighborhood Store', keywords: ['neighborhood', 'local', 'store', 'shop', 'small'], group: 'Shopping & Retail' },
		{ icon: '🛖', name: 'Roadside Stall', keywords: ['roadside', 'stall', 'street', 'vendor', 'market'], group: 'Shopping & Retail' },
		{ icon: '⛺', name: 'Market Tent', keywords: ['tent', 'stall', 'market', 'street market', 'vendor'], group: 'Shopping & Retail' },
		{ icon: '🎪', name: 'Market Booth', keywords: ['booth', 'stall', 'market', 'fair', 'vendor'], group: 'Shopping & Retail' },
		{ icon: '🏞️', name: 'Street Market', keywords: ['street market', 'open air', 'vendor', 'stall', 'outdoor'], group: 'Shopping & Retail' },
		{ icon: '🌾', name: 'Farm Stand', keywords: ['farm', 'stand', 'produce', 'roadside', 'fresh'], group: 'Shopping & Retail' },
		{ icon: '🍊', name: 'Fruit Stand', keywords: ['fruit', 'stand', 'vendor', 'stall', 'fresh'], group: 'Shopping & Retail' },
		{ icon: '🥖', name: 'Bakery', keywords: ['bakery', 'bread', 'shop', 'store', 'fresh'], group: 'Shopping & Retail' },
		{ icon: '🍰', name: 'Cake Shop', keywords: ['cake', 'pastry', 'shop', 'bakery', 'dessert'], group: 'Shopping & Retail' },
		{ icon: '🧃', name: 'Drink Stall', keywords: ['drink', 'beverage', 'stall', 'juice', 'vendor'], group: 'Shopping & Retail' },
		{ icon: '🍜', name: 'Food Stall', keywords: ['food', 'stall', 'street food', 'vendor', 'hawker'], group: 'Shopping & Retail' },
		{ icon: '☕', name: 'Coffee Shop', keywords: ['coffee', 'cafe', 'shop', 'beverage', 'stall'], group: 'Shopping & Retail' },

		// Beauty & Services
		{ icon: '💈', name: 'Barber Shop', keywords: ['barber', 'haircut', 'salon', 'grooming'], group: 'Shopping & Retail' },
		{ icon: '💅', name: 'Nail Salon', keywords: ['nail', 'salon', 'manicure', 'beauty'], group: 'Shopping & Retail' },
		{ icon: '💄', name: 'Cosmetics', keywords: ['cosmetics', 'makeup', 'beauty', 'lipstick'], group: 'Shopping & Retail' },

		// Clothing & Fashion
		{ icon: '👕', name: 'T-Shirt', keywords: ['shirt', 'clothes', 'clothing', 'wear'], group: 'Shopping & Retail' },
		{ icon: '👔', name: 'Necktie', keywords: ['tie', 'formal', 'clothes', 'business'], group: 'Shopping & Retail' },
		{ icon: '👗', name: 'Dress', keywords: ['dress', 'clothes', 'clothing', 'fashion'], group: 'Shopping & Retail' },
		{ icon: '👠', name: 'High Heel', keywords: ['shoe', 'heel', 'fashion', 'footwear'], group: 'Shopping & Retail' },
		{ icon: '👟', name: 'Sneaker', keywords: ['sneaker', 'shoe', 'sport', 'footwear'], group: 'Shopping & Retail' },
		{ icon: '👜', name: 'Handbag', keywords: ['handbag', 'bag', 'purse', 'fashion'], group: 'Shopping & Retail' },
		{ icon: '👝', name: 'Clutch Bag', keywords: ['clutch', 'bag', 'purse', 'fashion'], group: 'Shopping & Retail' },
		{ icon: '🎒', name: 'Backpack', keywords: ['backpack', 'bag', 'school', 'travel'], group: 'Shopping & Retail' },
		{ icon: '👓', name: 'Eyeglasses', keywords: ['glasses', 'eyeglasses', 'vision', 'optical'], group: 'Shopping & Retail' },
		{ icon: '🕶️', name: 'Sunglasses', keywords: ['sunglasses', 'shades', 'fashion', 'eyewear'], group: 'Shopping & Retail' },

		// Accessories & Jewelry
		{ icon: '⌚', name: 'Watch', keywords: ['watch', 'time', 'jewelry', 'accessory'], group: 'Shopping & Retail' },
		{ icon: '💍', name: 'Ring', keywords: ['ring', 'jewelry', 'wedding', 'diamond'], group: 'Shopping & Retail' },
		{ icon: '📿', name: 'Beads', keywords: ['beads', 'necklace', 'jewelry', 'accessories'], group: 'Shopping & Retail' },

		// Sports & Recreation
		{ icon: '🏀', name: 'Basketball', keywords: ['basketball', 'sport', 'ball', 'game'], group: 'Sports & Recreation' },
		{ icon: '⚽', name: 'Soccer Ball', keywords: ['soccer', 'football', 'sport', 'ball'], group: 'Sports & Recreation' },
		{ icon: '🏈', name: 'Football', keywords: ['football', 'american', 'sport', 'ball'], group: 'Sports & Recreation' },
		{ icon: '⚾', name: 'Baseball', keywords: ['baseball', 'sport', 'ball', 'game'], group: 'Sports & Recreation' },
		{ icon: '🥎', name: 'Softball', keywords: ['softball', 'sport', 'ball', 'game'], group: 'Sports & Recreation' },
		{ icon: '🎾', name: 'Tennis', keywords: ['tennis', 'sport', 'ball', 'racket'], group: 'Sports & Recreation' },
		{ icon: '🏐', name: 'Volleyball', keywords: ['volleyball', 'sport', 'ball', 'beach'], group: 'Sports & Recreation' },
		{ icon: '🏉', name: 'Rugby', keywords: ['rugby', 'sport', 'ball', 'game'], group: 'Sports & Recreation' },
		{ icon: '🥏', name: 'Flying Disc', keywords: ['frisbee', 'disc', 'sport', 'game'], group: 'Sports & Recreation' },
		{ icon: '🎱', name: 'Billiards', keywords: ['billiards', 'pool', 'snooker', 'sport'], group: 'Sports & Recreation' },
		{ icon: '🏓', name: 'Ping Pong', keywords: ['ping pong', 'table tennis', 'sport', 'paddle'], group: 'Sports & Recreation' },
		{ icon: '🏸', name: 'Badminton', keywords: ['badminton', 'sport', 'racket', 'shuttlecock'], group: 'Sports & Recreation' },
		{ icon: '🥅', name: 'Goal Net', keywords: ['goal', 'net', 'soccer', 'hockey'], group: 'Sports & Recreation' },
		{ icon: '🏒', name: 'Ice Hockey', keywords: ['hockey', 'ice', 'sport', 'stick'], group: 'Sports & Recreation' },
		{ icon: '🏑', name: 'Field Hockey', keywords: ['hockey', 'field', 'sport', 'stick'], group: 'Sports & Recreation' },
		{ icon: '🥍', name: 'Lacrosse', keywords: ['lacrosse', 'sport', 'stick', 'game'], group: 'Sports & Recreation' },
		{ icon: '🏏', name: 'Cricket', keywords: ['cricket', 'sport', 'bat', 'game'], group: 'Sports & Recreation' },
		{ icon: '🥊', name: 'Boxing', keywords: ['boxing', 'glove', 'sport', 'fight'], group: 'Sports & Recreation' },
		{ icon: '🥋', name: 'Martial Arts', keywords: ['martial arts', 'karate', 'judo', 'sport'], group: 'Sports & Recreation' },
		{ icon: '⛳', name: 'Golf', keywords: ['golf', 'sport', 'hole', 'flag'], group: 'Sports & Recreation' },
		{ icon: '🏹', name: 'Archery', keywords: ['archery', 'bow', 'arrow', 'sport'], group: 'Sports & Recreation' },
		{ icon: '🎣', name: 'Fishing', keywords: ['fishing', 'fish', 'rod', 'hobby'], group: 'Sports & Recreation' },
		{ icon: '🤿', name: 'Diving', keywords: ['diving', 'scuba', 'underwater', 'sport'], group: 'Sports & Recreation' },
		{ icon: '🏊', name: 'Swimming', keywords: ['swimming', 'pool', 'sport', 'water'], group: 'Sports & Recreation' },
		{ icon: '🏄', name: 'Surfing', keywords: ['surfing', 'surf', 'wave', 'sport'], group: 'Sports & Recreation' },
		{ icon: '🚣', name: 'Rowing', keywords: ['rowing', 'boat', 'paddle', 'sport'], group: 'Sports & Recreation' },
		{ icon: '🛶', name: 'Canoe', keywords: ['canoe', 'kayak', 'paddle', 'water'], group: 'Sports & Recreation' },
		{ icon: '🏇', name: 'Horse Racing', keywords: ['horse', 'racing', 'jockey', 'sport'], group: 'Sports & Recreation' },
		{ icon: '🚴', name: 'Cycling', keywords: ['cycling', 'bike', 'bicycle', 'sport'], group: 'Sports & Recreation' },
		{ icon: '🚵', name: 'Mountain Biking', keywords: ['mountain bike', 'cycling', 'offroad', 'sport'], group: 'Sports & Recreation' },
		{ icon: '🤸', name: 'Gymnastics', keywords: ['gymnastics', 'cartwheel', 'sport', 'acrobat'], group: 'Sports & Recreation' },
		{ icon: '🤼', name: 'Wrestling', keywords: ['wrestling', 'sport', 'fight', 'grappling'], group: 'Sports & Recreation' },
		{ icon: '🤺', name: 'Fencing', keywords: ['fencing', 'sword', 'sport', 'duel'], group: 'Sports & Recreation' },
		{ icon: '🤾', name: 'Handball', keywords: ['handball', 'sport', 'ball', 'game'], group: 'Sports & Recreation' },
		{ icon: '🧗', name: 'Rock Climbing', keywords: ['climbing', 'rock', 'sport', 'mountain'], group: 'Sports & Recreation' },
		{ icon: '🏋️', name: 'Weightlifting', keywords: ['gym', 'workout', 'fitness', 'weight'], group: 'Sports & Recreation' },
		{ icon: '🏃', name: 'Runner', keywords: ['running', 'jogging', 'fitness', 'sport'], group: 'Sports & Recreation' },
		{ icon: '🤹', name: 'Juggling', keywords: ['juggling', 'circus', 'skill', 'hobby'], group: 'Sports & Recreation' },
		{ icon: '🧘', name: 'Yoga', keywords: ['yoga', 'meditation', 'wellness', 'fitness'], group: 'Sports & Recreation' },
		{ icon: '⛷️', name: 'Skiing', keywords: ['skiing', 'ski', 'snow', 'winter'], group: 'Sports & Recreation' },
		{ icon: '🏂', name: 'Snowboarding', keywords: ['snowboard', 'snow', 'winter', 'sport'], group: 'Sports & Recreation' },
		{ icon: '⛸️', name: 'Ice Skating', keywords: ['skating', 'ice', 'winter', 'sport'], group: 'Sports & Recreation' },
		{ icon: '🛼', name: 'Roller Skating', keywords: ['roller', 'skating', 'skate', 'sport'], group: 'Sports & Recreation' },
		{ icon: '🛹', name: 'Skateboarding', keywords: ['skateboard', 'skating', 'sport', 'trick'], group: 'Sports & Recreation' },
		{ icon: '🏆', name: 'Trophy', keywords: ['trophy', 'award', 'win', 'champion'], group: 'Sports & Recreation' },
		{ icon: '🥇', name: 'Gold Medal', keywords: ['medal', 'gold', 'first', 'winner'], group: 'Sports & Recreation' },
		{ icon: '🥈', name: 'Silver Medal', keywords: ['medal', 'silver', 'second', 'runner-up'], group: 'Sports & Recreation' },
		{ icon: '🥉', name: 'Bronze Medal', keywords: ['medal', 'bronze', 'third', 'podium'], group: 'Sports & Recreation' },

		// Entertainment & Leisure
		{ icon: '🎮', name: 'Game Controller', keywords: ['game', 'gaming', 'video', 'play'], group: 'Entertainment & Leisure' },
		{ icon: '🎯', name: 'Target', keywords: ['target', 'bullseye', 'goal', 'aim'], group: 'Entertainment & Leisure' },
		{ icon: '🎲', name: 'Dice', keywords: ['dice', 'game', 'random', 'board game'], group: 'Entertainment & Leisure' },
		{ icon: '🎰', name: 'Slot Machine', keywords: ['slot', 'casino', 'gambling', 'luck'], group: 'Entertainment & Leisure' },
		{ icon: '🎬', name: 'Movie', keywords: ['movie', 'film', 'cinema', 'entertainment'], group: 'Entertainment & Leisure' },
		{ icon: '🎭', name: 'Theater', keywords: ['theater', 'drama', 'performance', 'arts'], group: 'Entertainment & Leisure' },
		{ icon: '🎨', name: 'Art', keywords: ['art', 'paint', 'palette', 'creative'], group: 'Entertainment & Leisure' },
		{ icon: '🎪', name: 'Circus', keywords: ['circus', 'tent', 'entertainment', 'show'], group: 'Entertainment & Leisure' },
		{ icon: '🎡', name: 'Ferris Wheel', keywords: ['ferris wheel', 'amusement', 'park', 'ride'], group: 'Entertainment & Leisure' },
		{ icon: '🎢', name: 'Roller Coaster', keywords: ['roller coaster', 'amusement', 'park', 'thrill'], group: 'Entertainment & Leisure' },
		{ icon: '🎠', name: 'Carousel', keywords: ['carousel', 'merry-go-round', 'amusement', 'park'], group: 'Entertainment & Leisure' },
		{ icon: '🎸', name: 'Guitar', keywords: ['guitar', 'music', 'instrument', 'rock'], group: 'Entertainment & Leisure' },
		{ icon: '🎹', name: 'Piano', keywords: ['piano', 'music', 'instrument', 'keys'], group: 'Entertainment & Leisure' },
		{ icon: '🎺', name: 'Trumpet', keywords: ['trumpet', 'music', 'instrument', 'brass'], group: 'Entertainment & Leisure' },
		{ icon: '🎻', name: 'Violin', keywords: ['violin', 'music', 'instrument', 'strings'], group: 'Entertainment & Leisure' },
		{ icon: '🥁', name: 'Drum', keywords: ['drum', 'music', 'instrument', 'percussion'], group: 'Entertainment & Leisure' },
		{ icon: '🎵', name: 'Music Note', keywords: ['music', 'note', 'song', 'melody'], group: 'Entertainment & Leisure' },
		{ icon: '🎶', name: 'Musical Notes', keywords: ['music', 'notes', 'song', 'melody'], group: 'Entertainment & Leisure' },
		{ icon: '🎤', name: 'Microphone', keywords: ['microphone', 'mic', 'singing', 'karaoke'], group: 'Entertainment & Leisure' },
		{ icon: '🎧', name: 'Headphones', keywords: ['headphones', 'music', 'audio', 'listen'], group: 'Entertainment & Leisure' },
		{ icon: '📷', name: 'Camera', keywords: ['camera', 'photo', 'picture', 'photography'], group: 'Entertainment & Leisure' },
		{ icon: '📹', name: 'Video Camera', keywords: ['video', 'camera', 'recording', 'film'], group: 'Entertainment & Leisure' },
		{ icon: '📺', name: 'Television', keywords: ['tv', 'television', 'screen', 'watch'], group: 'Entertainment & Leisure' },
		{ icon: '🎥', name: 'Movie Camera', keywords: ['movie', 'camera', 'film', 'cinema'], group: 'Entertainment & Leisure' },
		{ icon: '🎼', name: 'Musical Score', keywords: ['music', 'score', 'sheet', 'notes'], group: 'Entertainment & Leisure' },
		{ icon: '🎹', name: 'Keyboard', keywords: ['keyboard', 'piano', 'music', 'synthesizer'], group: 'Entertainment & Leisure' },
		{ icon: '🧩', name: 'Puzzle Piece', keywords: ['puzzle', 'game', 'jigsaw', 'hobby'], group: 'Entertainment & Leisure' },
		{ icon: '🎴', name: 'Playing Cards', keywords: ['cards', 'game', 'poker', 'playing'], group: 'Entertainment & Leisure' },
		{ icon: '🀄', name: 'Mahjong', keywords: ['mahjong', 'game', 'tile', 'chinese'], group: 'Entertainment & Leisure' },
		{ icon: '🎏', name: 'Kite', keywords: ['kite', 'flying', 'outdoor', 'hobby'], group: 'Entertainment & Leisure' },
		{ icon: '🎐', name: 'Wind Chime', keywords: ['wind chime', 'decoration', 'sound', 'outdoor'], group: 'Entertainment & Leisure' },
		{ icon: '🧶', name: 'Yarn', keywords: ['yarn', 'knitting', 'crafts', 'hobby'], group: 'Entertainment & Leisure' },
		{ icon: '🧵', name: 'Thread', keywords: ['thread', 'sewing', 'crafts', 'hobby'], group: 'Entertainment & Leisure' },
		{ icon: '🪡', name: 'Sewing Needle', keywords: ['sewing', 'needle', 'crafts', 'hobby'], group: 'Entertainment & Leisure' },
		{ icon: '🪢', name: 'Knot', keywords: ['knot', 'rope', 'crafts', 'tie'], group: 'Entertainment & Leisure' },

		// Technology & Devices
		{ icon: '📱', name: 'Phone', keywords: ['phone', 'mobile', 'smartphone', 'cell'], group: 'Technology & Devices' },
		{ icon: '💻', name: 'Laptop', keywords: ['laptop', 'computer', 'pc', 'work'], group: 'Technology & Devices' },
		{ icon: '🖥️', name: 'Desktop', keywords: ['desktop', 'computer', 'monitor', 'pc'], group: 'Technology & Devices' },
		{ icon: '⌨️', name: 'Keyboard', keywords: ['keyboard', 'typing', 'computer', 'input'], group: 'Technology & Devices' },
		{ icon: '🖱️', name: 'Mouse', keywords: ['mouse', 'computer', 'click', 'pointer'], group: 'Technology & Devices' },
		{ icon: '🖨️', name: 'Printer', keywords: ['printer', 'print', 'office', 'paper'], group: 'Technology & Devices' },
		{ icon: '📡', name: 'Satellite', keywords: ['satellite', 'antenna', 'signal', 'communication'], group: 'Technology & Devices' },
		{ icon: '🔋', name: 'Battery', keywords: ['battery', 'power', 'charge', 'energy'], group: 'Technology & Devices' },
		{ icon: '🔌', name: 'Electric Plug', keywords: ['plug', 'electric', 'power', 'outlet'], group: 'Technology & Devices' },
		{ icon: '💡', name: 'Light Bulb', keywords: ['bulb', 'light', 'idea', 'electricity'], group: 'Technology & Devices' },

		// Health & Medical
		{ icon: '💊', name: 'Pill', keywords: ['pill', 'medicine', 'drug', 'health'], group: 'Health & Medical' },
		{ icon: '💉', name: 'Syringe', keywords: ['syringe', 'injection', 'vaccine', 'medical'], group: 'Health & Medical' },
		{ icon: '🩺', name: 'Stethoscope', keywords: ['stethoscope', 'doctor', 'medical', 'health'], group: 'Health & Medical' },
		{ icon: '🩹', name: 'Bandage', keywords: ['bandage', 'adhesive', 'injury', 'medical'], group: 'Health & Medical' },
		{ icon: '🌡️', name: 'Thermometer', keywords: ['thermometer', 'temperature', 'fever', 'health'], group: 'Health & Medical' },
		{ icon: '🧴', name: 'Lotion', keywords: ['lotion', 'cream', 'skincare', 'bottle'], group: 'Health & Medical' },
		{ icon: '💆', name: 'Massage', keywords: ['massage', 'spa', 'relax', 'therapy'], group: 'Health & Medical' },
		{ icon: '🧘', name: 'Meditation', keywords: ['meditation', 'yoga', 'wellness', 'peace'], group: 'Health & Medical' },
		{ icon: '🧠', name: 'Brain', keywords: ['brain', 'mind', 'mental', 'health'], group: 'Health & Medical' },
		{ icon: '🧪', name: 'Test Tube', keywords: ['test tube', 'lab', 'science', 'medical'], group: 'Health & Medical' },
		{ icon: '🦷', name: 'Tooth', keywords: ['tooth', 'dental', 'dentist', 'care'], group: 'Health & Medical' },
		{ icon: '⚕️', name: 'Medical Symbol', keywords: ['medical', 'health', 'doctor', 'healthcare'], group: 'Health & Medical' },

		// Education & Work
		{ icon: '📚', name: 'Books', keywords: ['books', 'reading', 'library', 'study'], group: 'Education & Work' },
		{ icon: '📖', name: 'Open Book', keywords: ['book', 'reading', 'study', 'learn'], group: 'Education & Work' },
		{ icon: '📕', name: 'Closed Book', keywords: ['book', 'reading', 'textbook', 'study'], group: 'Education & Work' },
		{ icon: '📗', name: 'Green Book', keywords: ['book', 'reading', 'reference', 'study'], group: 'Education & Work' },
		{ icon: '📘', name: 'Blue Book', keywords: ['book', 'reading', 'manual', 'study'], group: 'Education & Work' },
		{ icon: '📙', name: 'Orange Book', keywords: ['book', 'reading', 'guide', 'study'], group: 'Education & Work' },
		{ icon: '📓', name: 'Notebook', keywords: ['notebook', 'notes', 'journal', 'writing'], group: 'Education & Work' },
		{ icon: '📔', name: 'Notebook with Cover', keywords: ['notebook', 'diary', 'journal', 'notes'], group: 'Education & Work' },
		{ icon: '📒', name: 'Ledger', keywords: ['ledger', 'accounting', 'record', 'business'], group: 'Education & Work' },
		{ icon: '📝', name: 'Memo', keywords: ['memo', 'note', 'writing', 'document'], group: 'Education & Work' },
		{ icon: '✏️', name: 'Pencil', keywords: ['pencil', 'writing', 'draw', 'school'], group: 'Education & Work' },
		{ icon: '✒️', name: 'Pen Nib', keywords: ['pen', 'writing', 'calligraphy', 'ink'], group: 'Education & Work' },
		{ icon: '🖊️', name: 'Pen', keywords: ['pen', 'writing', 'office', 'document'], group: 'Education & Work' },
		{ icon: '🖍️', name: 'Crayon', keywords: ['crayon', 'drawing', 'art', 'color'], group: 'Education & Work' },
		{ icon: '🖌️', name: 'Paintbrush', keywords: ['brush', 'paint', 'art', 'creative'], group: 'Education & Work' },
		{ icon: '📄', name: 'Page Facing Up', keywords: ['document', 'paper', 'file', 'page'], group: 'Education & Work' },
		{ icon: '📃', name: 'Page with Curl', keywords: ['document', 'paper', 'page', 'file'], group: 'Education & Work' },
		{ icon: '📑', name: 'Bookmark Tabs', keywords: ['bookmark', 'tabs', 'organize', 'reference'], group: 'Education & Work' },
		{ icon: '🔖', name: 'Bookmark', keywords: ['bookmark', 'save', 'reference', 'mark'], group: 'Education & Work' },
		{ icon: '📁', name: 'Folder', keywords: ['folder', 'file', 'organize', 'documents'], group: 'Education & Work' },
		{ icon: '📂', name: 'Open Folder', keywords: ['folder', 'open', 'files', 'documents'], group: 'Education & Work' },
		{ icon: '🗂️', name: 'Card Index Dividers', keywords: ['dividers', 'organize', 'files', 'index'], group: 'Education & Work' },
		{ icon: '🗃️', name: 'Card File Box', keywords: ['filing', 'storage', 'organize', 'archive'], group: 'Education & Work' },
		{ icon: '🗄️', name: 'File Cabinet', keywords: ['cabinet', 'filing', 'storage', 'office'], group: 'Education & Work' },
		{ icon: '📋', name: 'Clipboard', keywords: ['clipboard', 'checklist', 'notes', 'office'], group: 'Education & Work' },
		{ icon: '📊', name: 'Bar Chart', keywords: ['chart', 'graph', 'statistics', 'data'], group: 'Education & Work' },
		{ icon: '📈', name: 'Chart Increasing', keywords: ['chart', 'growth', 'increase', 'trend'], group: 'Education & Work' },
		{ icon: '📉', name: 'Chart Decreasing', keywords: ['chart', 'decline', 'decrease', 'down'], group: 'Education & Work' },
		{ icon: '🗓️', name: 'Spiral Calendar', keywords: ['calendar', 'schedule', 'date', 'planner'], group: 'Education & Work' },
		{ icon: '📆', name: 'Tear-Off Calendar', keywords: ['calendar', 'date', 'day', 'schedule'], group: 'Education & Work' },
		{ icon: '📅', name: 'Calendar', keywords: ['calendar', 'date', 'schedule', 'plan'], group: 'Education & Work' },
		{ icon: '🗒️', name: 'Spiral Notepad', keywords: ['notepad', 'notes', 'writing', 'memo'], group: 'Education & Work' },
		{ icon: '🗞️', name: 'Rolled-Up Newspaper', keywords: ['newspaper', 'news', 'media', 'press'], group: 'Education & Work' },
		{ icon: '📰', name: 'Newspaper', keywords: ['newspaper', 'news', 'media', 'reading'], group: 'Education & Work' },
		{ icon: '🎓', name: 'Graduation Cap', keywords: ['graduation', 'education', 'school', 'degree'], group: 'Education & Work' },
		{ icon: '🔬', name: 'Microscope', keywords: ['microscope', 'science', 'lab', 'research'], group: 'Education & Work' },
		{ icon: '🔭', name: 'Telescope', keywords: ['telescope', 'astronomy', 'space', 'science'], group: 'Education & Work' },
		{ icon: '📐', name: 'Triangular Ruler', keywords: ['ruler', 'triangle', 'math', 'geometry'], group: 'Education & Work' },
		{ icon: '📏', name: 'Straight Ruler', keywords: ['ruler', 'measure', 'school', 'straight'], group: 'Education & Work' },
		{ icon: '🧮', name: 'Abacus', keywords: ['abacus', 'math', 'calculate', 'counting'], group: 'Education & Work' },
		{ icon: '📌', name: 'Pushpin', keywords: ['pin', 'pushpin', 'tack', 'attach'], group: 'Education & Work' },
		{ icon: '📍', name: 'Round Pushpin', keywords: ['pin', 'location', 'marker', 'place'], group: 'Education & Work' },
		{ icon: '✂️', name: 'Scissors', keywords: ['scissors', 'cut', 'office', 'tool'], group: 'Education & Work' },
		{ icon: '🖇️', name: 'Linked Paperclips', keywords: ['paperclip', 'attach', 'office', 'link'], group: 'Education & Work' },
		{ icon: '📎', name: 'Paperclip', keywords: ['paperclip', 'attach', 'office', 'clip'], group: 'Education & Work' },
		{ icon: '📏', name: 'Ruler', keywords: ['ruler', 'measure', 'length', 'tool'], group: 'Education & Work' },
		{ icon: '💼', name: 'Briefcase', keywords: ['briefcase', 'business', 'work', 'office'], group: 'Education & Work' },
		{ icon: '👔', name: 'Necktie', keywords: ['tie', 'formal', 'business', 'professional'], group: 'Education & Work' },
		{ icon: '🎯', name: 'Direct Hit', keywords: ['target', 'goal', 'objective', 'achievement'], group: 'Education & Work' },
		{ icon: '🏆', name: 'Trophy', keywords: ['trophy', 'award', 'achievement', 'success'], group: 'Education & Work' },
		{ icon: '🥇', name: 'Gold Medal', keywords: ['medal', 'gold', 'first', 'achievement'], group: 'Education & Work' },
		{ icon: '🎖️', name: 'Military Medal', keywords: ['medal', 'award', 'honor', 'achievement'], group: 'Education & Work' },
		{ icon: '📞', name: 'Telephone', keywords: ['phone', 'call', 'business', 'contact'], group: 'Education & Work' },
		{ icon: '☎️', name: 'Telephone', keywords: ['phone', 'landline', 'office', 'call'], group: 'Education & Work' },
		{ icon: '📟', name: 'Pager', keywords: ['pager', 'beeper', 'communication', 'device'], group: 'Education & Work' },
		{ icon: '📠', name: 'Fax Machine', keywords: ['fax', 'machine', 'office', 'document'], group: 'Education & Work' },
		{ icon: '🖨️', name: 'Printer', keywords: ['printer', 'print', 'office', 'document'], group: 'Education & Work' },
		{ icon: '🖥️', name: 'Desktop Computer', keywords: ['computer', 'desktop', 'work', 'office'], group: 'Education & Work' },
		{ icon: '💻', name: 'Laptop', keywords: ['laptop', 'computer', 'work', 'portable'], group: 'Education & Work' },
		{ icon: '⌨️', name: 'Keyboard', keywords: ['keyboard', 'typing', 'computer', 'input'], group: 'Education & Work' },
		{ icon: '🖱️', name: 'Computer Mouse', keywords: ['mouse', 'computer', 'click', 'pointer'], group: 'Education & Work' },
		{ icon: '🖲️', name: 'Trackball', keywords: ['trackball', 'mouse', 'computer', 'input'], group: 'Education & Work' },
		{ icon: '💾', name: 'Floppy Disk', keywords: ['floppy', 'disk', 'save', 'storage'], group: 'Education & Work' },
		{ icon: '💿', name: 'Optical Disk', keywords: ['cd', 'disk', 'storage', 'media'], group: 'Education & Work' },
		{ icon: '📀', name: 'DVD', keywords: ['dvd', 'disk', 'storage', 'media'], group: 'Education & Work' },
		{ icon: '🗜️', name: 'Clamp', keywords: ['clamp', 'tool', 'compress', 'hold'], group: 'Education & Work' },
		{ icon: '⚖️', name: 'Balance Scale', keywords: ['scale', 'balance', 'justice', 'law'], group: 'Education & Work' },
		{ icon: '🔨', name: 'Hammer', keywords: ['hammer', 'tool', 'build', 'work'], group: 'Education & Work' },
		{ icon: '🔧', name: 'Wrench', keywords: ['wrench', 'tool', 'repair', 'fix'], group: 'Education & Work' },
		{ icon: '⚙️', name: 'Gear', keywords: ['gear', 'settings', 'mechanical', 'work'], group: 'Education & Work' },
		{ icon: '🗂️', name: 'Dividers', keywords: ['dividers', 'organize', 'filing', 'tabs'], group: 'Education & Work' },
		{ icon: '📜', name: 'Scroll', keywords: ['scroll', 'document', 'certificate', 'ancient'], group: 'Education & Work' },

		// Utilities & Services
		{ icon: '🔧', name: 'Wrench', keywords: ['wrench', 'tool', 'repair', 'fix'], group: 'Utilities & Services' },
		{ icon: '🔨', name: 'Hammer', keywords: ['hammer', 'tool', 'build', 'fix'], group: 'Utilities & Services' },
		{ icon: '🪛', name: 'Screwdriver', keywords: ['screwdriver', 'tool', 'repair', 'fix'], group: 'Utilities & Services' },
		{ icon: '⚡', name: 'Lightning', keywords: ['lightning', 'electric', 'power', 'energy'], group: 'Utilities & Services' },
		{ icon: '🔥', name: 'Fire', keywords: ['fire', 'flame', 'hot', 'heat'], group: 'Utilities & Services' },
		{ icon: '💧', name: 'Water Drop', keywords: ['water', 'drop', 'liquid', 'utility'], group: 'Utilities & Services' },
		{ icon: '🚿', name: 'Shower', keywords: ['shower', 'bath', 'water', 'clean'], group: 'Utilities & Services' },
		{ icon: '🚽', name: 'Toilet', keywords: ['toilet', 'bathroom', 'wc', 'restroom'], group: 'Utilities & Services' },
		{ icon: '📞', name: 'Telephone', keywords: ['phone', 'telephone', 'call', 'contact'], group: 'Utilities & Services' },
		{ icon: '📧', name: 'Email', keywords: ['email', 'mail', 'message', 'inbox'], group: 'Utilities & Services' },
		{ icon: '📮', name: 'Mailbox', keywords: ['mailbox', 'post', 'mail', 'letter'], group: 'Utilities & Services' },
		{ icon: '🔒', name: 'Lock', keywords: ['lock', 'secure', 'security', 'safe'], group: 'Utilities & Services' },
		{ icon: '🔑', name: 'Key', keywords: ['key', 'unlock', 'access', 'security'], group: 'Utilities & Services' },
		{ icon: '🗑️', name: 'Trash', keywords: ['trash', 'garbage', 'delete', 'waste'], group: 'Utilities & Services' },
		{ icon: '♻️', name: 'Recycle', keywords: ['recycle', 'reuse', 'green', 'environment'], group: 'Utilities & Services' },
		{ icon: '🛡️', name: 'Shield', keywords: ['shield', 'protection', 'security', 'insurance'], group: 'Utilities & Services' },
		{ icon: '🛋️', name: 'Couch', keywords: ['couch', 'sofa', 'furniture', 'home'], group: 'Utilities & Services' },
		{ icon: '🧹', name: 'Broom', keywords: ['broom', 'cleaning', 'sweep', 'clean'], group: 'Utilities & Services' },
		{ icon: '🔐', name: 'Locked with Key', keywords: ['locked', 'key', 'security', 'safe'], group: 'Utilities & Services' },
		{ icon: '✉️', name: 'Envelope', keywords: ['envelope', 'mail', 'letter', 'message'], group: 'Utilities & Services' },

		// Nature & Weather
		{ icon: '🌞', name: 'Sun with Face', keywords: ['sun', 'sunny', 'day', 'bright'], group: 'Nature & Weather' },
		{ icon: '🌙', name: 'Crescent Moon', keywords: ['moon', 'night', 'lunar', 'crescent'], group: 'Nature & Weather' },
		{ icon: '🌛', name: 'First Quarter Moon', keywords: ['moon', 'night', 'phase', 'quarter'], group: 'Nature & Weather' },
		{ icon: '🌜', name: 'Last Quarter Moon', keywords: ['moon', 'night', 'phase', 'quarter'], group: 'Nature & Weather' },
		{ icon: '🌝', name: 'Full Moon Face', keywords: ['moon', 'full', 'night', 'face'], group: 'Nature & Weather' },
		{ icon: '🌚', name: 'New Moon Face', keywords: ['moon', 'new', 'dark', 'night'], group: 'Nature & Weather' },
		{ icon: '⭐', name: 'Star', keywords: ['star', 'night', 'shine', 'favorite'], group: 'Nature & Weather' },
		{ icon: '🌟', name: 'Glowing Star', keywords: ['star', 'glowing', 'shine', 'sparkle'], group: 'Nature & Weather' },
		{ icon: '✨', name: 'Sparkles', keywords: ['sparkle', 'shine', 'glitter', 'magic'], group: 'Nature & Weather' },
		{ icon: '⚡', name: 'Lightning', keywords: ['lightning', 'electric', 'bolt', 'weather'], group: 'Nature & Weather' },
		{ icon: '☀️', name: 'Sun', keywords: ['sun', 'sunny', 'bright', 'weather'], group: 'Nature & Weather' },
		{ icon: '⛅', name: 'Sun Behind Cloud', keywords: ['cloud', 'cloudy', 'weather', 'partly'], group: 'Nature & Weather' },
		{ icon: '☁️', name: 'Cloud', keywords: ['cloud', 'weather', 'sky', 'overcast'], group: 'Nature & Weather' },
		{ icon: '🌤️', name: 'Sun Behind Small Cloud', keywords: ['sun', 'cloud', 'weather', 'partly sunny'], group: 'Nature & Weather' },
		{ icon: '🌥️', name: 'Sun Behind Large Cloud', keywords: ['sun', 'cloud', 'weather', 'overcast'], group: 'Nature & Weather' },
		{ icon: '🌦️', name: 'Sun Behind Rain Cloud', keywords: ['rain', 'sun', 'weather', 'shower'], group: 'Nature & Weather' },
		{ icon: '🌧️', name: 'Rain Cloud', keywords: ['rain', 'rainy', 'weather', 'wet'], group: 'Nature & Weather' },
		{ icon: '⛈️', name: 'Storm', keywords: ['storm', 'thunder', 'lightning', 'weather'], group: 'Nature & Weather' },
		{ icon: '🌩️', name: 'Cloud with Lightning', keywords: ['lightning', 'thunder', 'storm', 'weather'], group: 'Nature & Weather' },
		{ icon: '🌨️', name: 'Snow Cloud', keywords: ['snow', 'snowy', 'winter', 'cold'], group: 'Nature & Weather' },
		{ icon: '❄️', name: 'Snowflake', keywords: ['snowflake', 'snow', 'winter', 'cold'], group: 'Nature & Weather' },
		{ icon: '☃️', name: 'Snowman', keywords: ['snowman', 'winter', 'snow', 'cold'], group: 'Nature & Weather' },
		{ icon: '⛄', name: 'Snowman Without Snow', keywords: ['snowman', 'winter', 'snow', 'olaf'], group: 'Nature & Weather' },
		{ icon: '🌬️', name: 'Wind Face', keywords: ['wind', 'blow', 'breeze', 'weather'], group: 'Nature & Weather' },
		{ icon: '💨', name: 'Dashing Away', keywords: ['wind', 'dash', 'fast', 'breeze'], group: 'Nature & Weather' },
		{ icon: '🌪️', name: 'Tornado', keywords: ['tornado', 'cyclone', 'storm', 'weather'], group: 'Nature & Weather' },
		{ icon: '🌫️', name: 'Fog', keywords: ['fog', 'mist', 'weather', 'hazy'], group: 'Nature & Weather' },
		{ icon: '🌈', name: 'Rainbow', keywords: ['rainbow', 'colors', 'weather', 'colorful'], group: 'Nature & Weather' },
		{ icon: '☔', name: 'Umbrella with Rain', keywords: ['umbrella', 'rain', 'weather', 'wet'], group: 'Nature & Weather' },
		{ icon: '⛱️', name: 'Beach Umbrella', keywords: ['umbrella', 'beach', 'sun', 'vacation'], group: 'Nature & Weather' },
		{ icon: '💧', name: 'Droplet', keywords: ['water', 'drop', 'liquid', 'droplet'], group: 'Nature & Weather' },
		{ icon: '💦', name: 'Sweat Droplets', keywords: ['water', 'sweat', 'drops', 'splash'], group: 'Nature & Weather' },
		{ icon: '🌊', name: 'Wave', keywords: ['wave', 'ocean', 'sea', 'water'], group: 'Nature & Weather' },
		{ icon: '🌳', name: 'Deciduous Tree', keywords: ['tree', 'nature', 'plant', 'green'], group: 'Nature & Weather' },
		{ icon: '🌲', name: 'Evergreen Tree', keywords: ['pine', 'tree', 'forest', 'evergreen'], group: 'Nature & Weather' },
		{ icon: '🌴', name: 'Palm Tree', keywords: ['palm', 'tree', 'tropical', 'beach'], group: 'Nature & Weather' },
		{ icon: '🌱', name: 'Seedling', keywords: ['seedling', 'plant', 'grow', 'nature'], group: 'Nature & Weather' },
		{ icon: '🌿', name: 'Herb', keywords: ['herb', 'leaf', 'plant', 'nature'], group: 'Nature & Weather' },
		{ icon: '☘️', name: 'Shamrock', keywords: ['shamrock', 'clover', 'irish', 'luck'], group: 'Nature & Weather' },
		{ icon: '🍀', name: 'Four Leaf Clover', keywords: ['clover', 'lucky', 'four leaf', 'fortune'], group: 'Nature & Weather' },
		{ icon: '🎋', name: 'Tanabata Tree', keywords: ['bamboo', 'tree', 'japanese', 'decoration'], group: 'Nature & Weather' },
		{ icon: '🎍', name: 'Pine Decoration', keywords: ['pine', 'decoration', 'japanese', 'new year'], group: 'Nature & Weather' },
		{ icon: '🍃', name: 'Leaves', keywords: ['leaves', 'wind', 'nature', 'autumn'], group: 'Nature & Weather' },
		{ icon: '🍂', name: 'Fallen Leaf', keywords: ['leaf', 'autumn', 'fall', 'nature'], group: 'Nature & Weather' },
		{ icon: '🍁', name: 'Maple Leaf', keywords: ['maple', 'leaf', 'autumn', 'canada'], group: 'Nature & Weather' },
		{ icon: '🌾', name: 'Sheaf of Rice', keywords: ['rice', 'grain', 'harvest', 'nature'], group: 'Nature & Weather' },
		{ icon: '🌵', name: 'Cactus', keywords: ['cactus', 'desert', 'plant', 'succulent'], group: 'Nature & Weather' },
		{ icon: '🌾', name: 'Ear of Rice', keywords: ['rice', 'grain', 'wheat', 'harvest'], group: 'Nature & Weather' },
		{ icon: '🪴', name: 'Potted Plant', keywords: ['plant', 'pot', 'indoor', 'houseplant'], group: 'Nature & Weather' },
		{ icon: '🌺', name: 'Hibiscus', keywords: ['flower', 'hibiscus', 'tropical', 'nature'], group: 'Nature & Weather' },
		{ icon: '🌻', name: 'Sunflower', keywords: ['sunflower', 'flower', 'yellow', 'nature'], group: 'Nature & Weather' },
		{ icon: '🌹', name: 'Rose', keywords: ['rose', 'flower', 'love', 'romance'], group: 'Nature & Weather' },
		{ icon: '🥀', name: 'Wilted Flower', keywords: ['wilted', 'flower', 'dead', 'sad'], group: 'Nature & Weather' },
		{ icon: '🌷', name: 'Tulip', keywords: ['tulip', 'flower', 'spring', 'netherlands'], group: 'Nature & Weather' },
		{ icon: '🌼', name: 'Blossom', keywords: ['blossom', 'flower', 'daisy', 'nature'], group: 'Nature & Weather' },
		{ icon: '🌸', name: 'Cherry Blossom', keywords: ['cherry', 'blossom', 'sakura', 'spring'], group: 'Nature & Weather' },
		{ icon: '💐', name: 'Bouquet', keywords: ['bouquet', 'flowers', 'gift', 'arrangement'], group: 'Nature & Weather' },
		{ icon: '🏵️', name: 'Rosette', keywords: ['rosette', 'flower', 'award', 'decoration'], group: 'Nature & Weather' },
		{ icon: '🪷', name: 'Lotus', keywords: ['lotus', 'flower', 'meditation', 'water'], group: 'Nature & Weather' },
		{ icon: '🌍', name: 'Earth Globe Europe-Africa', keywords: ['earth', 'globe', 'world', 'planet'], group: 'Nature & Weather' },
		{ icon: '🌎', name: 'Earth Globe Americas', keywords: ['earth', 'globe', 'world', 'planet'], group: 'Nature & Weather' },
		{ icon: '🌏', name: 'Earth Globe Asia-Australia', keywords: ['earth', 'globe', 'world', 'planet'], group: 'Nature & Weather' },
		{ icon: '🌐', name: 'Globe with Meridians', keywords: ['globe', 'world', 'internet', 'international'], group: 'Nature & Weather' },
		{ icon: '🏔️', name: 'Snow-Capped Mountain', keywords: ['mountain', 'snow', 'peak', 'nature'], group: 'Nature & Weather' },
		{ icon: '⛰️', name: 'Mountain', keywords: ['mountain', 'peak', 'nature', 'hiking'], group: 'Nature & Weather' },
		{ icon: '🗻', name: 'Mount Fuji', keywords: ['fuji', 'mountain', 'japan', 'volcano'], group: 'Nature & Weather' },
		{ icon: '🌋', name: 'Volcano', keywords: ['volcano', 'eruption', 'lava', 'nature'], group: 'Nature & Weather' },
		{ icon: '🏕️', name: 'Camping', keywords: ['camping', 'tent', 'outdoor', 'nature'], group: 'Nature & Weather' },
		{ icon: '🏖️', name: 'Beach', keywords: ['beach', 'umbrella', 'sand', 'ocean'], group: 'Nature & Weather' },
		{ icon: '🏜️', name: 'Desert', keywords: ['desert', 'sand', 'dry', 'hot'], group: 'Nature & Weather' },
		{ icon: '🏝️', name: 'Desert Island', keywords: ['island', 'tropical', 'palm', 'beach'], group: 'Nature & Weather' },
		{ icon: '🏞️', name: 'National Park', keywords: ['park', 'nature', 'outdoor', 'scenic'], group: 'Nature & Weather' },
		{ icon: '🦋', name: 'Butterfly', keywords: ['butterfly', 'insect', 'nature', 'pretty'], group: 'Nature & Weather' },
		{ icon: '🐛', name: 'Bug', keywords: ['bug', 'insect', 'caterpillar', 'nature'], group: 'Nature & Weather' },
		{ icon: '🐝', name: 'Honeybee', keywords: ['bee', 'honey', 'insect', 'nature'], group: 'Nature & Weather' },
		{ icon: '🐞', name: 'Lady Beetle', keywords: ['ladybug', 'beetle', 'insect', 'nature'], group: 'Nature & Weather' },
		{ icon: '🦗', name: 'Cricket', keywords: ['cricket', 'insect', 'nature', 'sound'], group: 'Nature & Weather' },
		{ icon: '🕷️', name: 'Spider', keywords: ['spider', 'insect', 'web', 'nature'], group: 'Nature & Weather' },
		{ icon: '🕸️', name: 'Spider Web', keywords: ['web', 'spider', 'nature', 'halloween'], group: 'Nature & Weather' },
		{ icon: '🐚', name: 'Spiral Shell', keywords: ['shell', 'seashell', 'beach', 'ocean'], group: 'Nature & Weather' },
		{ icon: '🪨', name: 'Rock', keywords: ['rock', 'stone', 'nature', 'geology'], group: 'Nature & Weather' },
		{ icon: '🪵', name: 'Wood', keywords: ['wood', 'log', 'timber', 'nature'], group: 'Nature & Weather' },

		// Travel & Trips
		{ icon: '✈️', name: 'Airplane', keywords: ['airplane', 'flight', 'travel', 'vacation'], group: 'Travel & Trips' },
		{ icon: '🛫', name: 'Airplane Departure', keywords: ['airplane', 'departure', 'takeoff', 'travel'], group: 'Travel & Trips' },
		{ icon: '🛬', name: 'Airplane Arrival', keywords: ['airplane', 'arrival', 'landing', 'travel'], group: 'Travel & Trips' },
		{ icon: '🧳', name: 'Luggage', keywords: ['luggage', 'suitcase', 'travel', 'baggage'], group: 'Travel & Trips' },
		{ icon: '💺', name: 'Airplane Seat', keywords: ['seat', 'airplane', 'flight', 'travel'], group: 'Travel & Trips' },
		{ icon: '🛂', name: 'Passport Control', keywords: ['passport', 'control', 'immigration', 'travel'], group: 'Travel & Trips' },
		{ icon: '🛃', name: 'Customs', keywords: ['customs', 'luggage', 'travel', 'border'], group: 'Travel & Trips' },
		{ icon: '🛄', name: 'Baggage Claim', keywords: ['baggage', 'claim', 'luggage', 'airport'], group: 'Travel & Trips' },
		{ icon: '🛅', name: 'Left Luggage', keywords: ['luggage', 'locker', 'storage', 'travel'], group: 'Travel & Trips' },
		{ icon: '🗺️', name: 'World Map', keywords: ['map', 'world', 'travel', 'navigation'], group: 'Travel & Trips' },
		{ icon: '🗾', name: 'Map of Japan', keywords: ['japan', 'map', 'travel', 'country'], group: 'Travel & Trips' },
		{ icon: '🧭', name: 'Compass', keywords: ['compass', 'navigation', 'direction', 'travel'], group: 'Travel & Trips' },
		{ icon: '🏨', name: 'Hotel', keywords: ['hotel', 'accommodation', 'lodging', 'travel'], group: 'Travel & Trips' },
		{ icon: '🏩', name: 'Love Hotel', keywords: ['hotel', 'love', 'accommodation', 'japan'], group: 'Travel & Trips' },
		{ icon: '🏕️', name: 'Camping', keywords: ['camping', 'tent', 'outdoor', 'adventure'], group: 'Travel & Trips' },
		{ icon: '⛺', name: 'Tent', keywords: ['tent', 'camping', 'outdoor', 'adventure'], group: 'Travel & Trips' },
		{ icon: '🏖️', name: 'Beach with Umbrella', keywords: ['beach', 'vacation', 'sand', 'relax'], group: 'Travel & Trips' },
		{ icon: '🏝️', name: 'Desert Island', keywords: ['island', 'vacation', 'tropical', 'paradise'], group: 'Travel & Trips' },
		{ icon: '🗽', name: 'Statue of Liberty', keywords: ['statue', 'liberty', 'new york', 'landmark'], group: 'Travel & Trips' },
		{ icon: '🗼', name: 'Tokyo Tower', keywords: ['tower', 'tokyo', 'japan', 'landmark'], group: 'Travel & Trips' },
		{ icon: '🗿', name: 'Moai', keywords: ['moai', 'easter island', 'statue', 'landmark'], group: 'Travel & Trips' },
		{ icon: '🕌', name: 'Mosque', keywords: ['mosque', 'religion', 'travel', 'architecture'], group: 'Travel & Trips' },
		{ icon: '🕍', name: 'Synagogue', keywords: ['synagogue', 'religion', 'travel', 'architecture'], group: 'Travel & Trips' },
		{ icon: '⛩️', name: 'Shinto Shrine', keywords: ['shrine', 'shinto', 'japan', 'travel'], group: 'Travel & Trips' },
		{ icon: '🕋', name: 'Kaaba', keywords: ['kaaba', 'mecca', 'islam', 'pilgrimage'], group: 'Travel & Trips' },
		{ icon: '⛲', name: 'Fountain', keywords: ['fountain', 'water', 'park', 'landmark'], group: 'Travel & Trips' },
		{ icon: '🎢', name: 'Roller Coaster', keywords: ['roller coaster', 'amusement', 'park', 'fun'], group: 'Travel & Trips' },
		{ icon: '🎡', name: 'Ferris Wheel', keywords: ['ferris wheel', 'amusement', 'park', 'attraction'], group: 'Travel & Trips' },
		{ icon: '🎠', name: 'Carousel Horse', keywords: ['carousel', 'amusement', 'park', 'ride'], group: 'Travel & Trips' },
		{ icon: '🏰', name: 'Castle', keywords: ['castle', 'palace', 'fortress', 'travel'], group: 'Travel & Trips' },
		{ icon: '🏯', name: 'Japanese Castle', keywords: ['castle', 'japan', 'palace', 'travel'], group: 'Travel & Trips' },
		{ icon: '🏟️', name: 'Stadium', keywords: ['stadium', 'arena', 'sports', 'venue'], group: 'Travel & Trips' },
		{ icon: '🎪', name: 'Circus Tent', keywords: ['circus', 'tent', 'entertainment', 'show'], group: 'Travel & Trips' },
		{ icon: '🚢', name: 'Ship', keywords: ['ship', 'cruise', 'ocean', 'travel'], group: 'Travel & Trips' },
		{ icon: '⛴️', name: 'Ferry', keywords: ['ferry', 'boat', 'water', 'transport'], group: 'Travel & Trips' },
		{ icon: '🛳️', name: 'Passenger Ship', keywords: ['cruise', 'ship', 'passenger', 'vacation'], group: 'Travel & Trips' },
		{ icon: '⛵', name: 'Sailboat', keywords: ['sailboat', 'sailing', 'yacht', 'vacation'], group: 'Travel & Trips' },
		{ icon: '🚂', name: 'Locomotive', keywords: ['train', 'locomotive', 'railway', 'travel'], group: 'Travel & Trips' },
		{ icon: '🚆', name: 'Train', keywords: ['train', 'railway', 'travel', 'transport'], group: 'Travel & Trips' },
		{ icon: '🚄', name: 'High-Speed Train', keywords: ['train', 'bullet', 'fast', 'travel'], group: 'Travel & Trips' },
		{ icon: '🚅', name: 'Bullet Train', keywords: ['train', 'shinkansen', 'fast', 'japan'], group: 'Travel & Trips' },
		{ icon: '🚇', name: 'Metro', keywords: ['metro', 'subway', 'underground', 'transit'], group: 'Travel & Trips' },
		{ icon: '🚌', name: 'Bus', keywords: ['bus', 'transport', 'public', 'travel'], group: 'Travel & Trips' },
		{ icon: '🚐', name: 'Minibus', keywords: ['minibus', 'van', 'transport', 'travel'], group: 'Travel & Trips' },
		{ icon: '🚗', name: 'Automobile', keywords: ['car', 'auto', 'vehicle', 'road trip'], group: 'Travel & Trips' },
		{ icon: '🚙', name: 'SUV', keywords: ['suv', 'car', 'vehicle', 'road trip'], group: 'Travel & Trips' },
		{ icon: '🚕', name: 'Taxi', keywords: ['taxi', 'cab', 'transport', 'travel'], group: 'Travel & Trips' },
		{ icon: '🛺', name: 'Auto Rickshaw', keywords: ['rickshaw', 'tuk tuk', 'transport', 'travel'], group: 'Travel & Trips' },
		{ icon: '🚲', name: 'Bicycle', keywords: ['bicycle', 'bike', 'cycling', 'travel'], group: 'Travel & Trips' },
		{ icon: '🛴', name: 'Scooter', keywords: ['scooter', 'kick', 'transport', 'travel'], group: 'Travel & Trips' },
		{ icon: '🛵', name: 'Motor Scooter', keywords: ['scooter', 'motorcycle', 'moped', 'travel'], group: 'Travel & Trips' },
		{ icon: '🏍️', name: 'Motorcycle', keywords: ['motorcycle', 'bike', 'motor', 'travel'], group: 'Travel & Trips' },
		{ icon: '🚁', name: 'Helicopter', keywords: ['helicopter', 'chopper', 'flight', 'travel'], group: 'Travel & Trips' },
		{ icon: '🚠', name: 'Mountain Cableway', keywords: ['cable car', 'mountain', 'gondola', 'travel'], group: 'Travel & Trips' },
		{ icon: '🚡', name: 'Aerial Tramway', keywords: ['tramway', 'aerial', 'cable', 'sightseeing'], group: 'Travel & Trips' },
		{ icon: '🛶', name: 'Canoe', keywords: ['canoe', 'kayak', 'paddle', 'adventure'], group: 'Travel & Trips' },
		{ icon: '🎿', name: 'Skis', keywords: ['ski', 'skiing', 'winter', 'vacation'], group: 'Travel & Trips' },
		{ icon: '🏂', name: 'Snowboarder', keywords: ['snowboard', 'winter', 'sport', 'vacation'], group: 'Travel & Trips' },
		{ icon: '🏄', name: 'Surfer', keywords: ['surfing', 'surf', 'wave', 'beach'], group: 'Travel & Trips' },
		{ icon: '🤿', name: 'Diving Mask', keywords: ['diving', 'scuba', 'snorkel', 'underwater'], group: 'Travel & Trips' },
		{ icon: '🏊', name: 'Swimmer', keywords: ['swimming', 'pool', 'ocean', 'vacation'], group: 'Travel & Trips' },
		{ icon: '⛱️', name: 'Beach Umbrella', keywords: ['umbrella', 'beach', 'sun', 'vacation'], group: 'Travel & Trips' },
		{ icon: '🩱', name: 'One-Piece Swimsuit', keywords: ['swimsuit', 'swimming', 'beach', 'vacation'], group: 'Travel & Trips' },
		{ icon: '🩳', name: 'Shorts', keywords: ['shorts', 'summer', 'beach', 'casual'], group: 'Travel & Trips' },
		{ icon: '🕶️', name: 'Sunglasses', keywords: ['sunglasses', 'shades', 'sun', 'vacation'], group: 'Travel & Trips' },
		{ icon: '🎒', name: 'Backpack', keywords: ['backpack', 'bag', 'travel', 'hiking'], group: 'Travel & Trips' },
		{ icon: '📷', name: 'Camera', keywords: ['camera', 'photo', 'photography', 'memories'], group: 'Travel & Trips' },
		{ icon: '📸', name: 'Camera with Flash', keywords: ['camera', 'photo', 'flash', 'picture'], group: 'Travel & Trips' },
		{ icon: '🎥', name: 'Movie Camera', keywords: ['video', 'camera', 'film', 'recording'], group: 'Travel & Trips' },
		{ icon: '🎬', name: 'Clapper Board', keywords: ['movie', 'film', 'cinema', 'action'], group: 'Travel & Trips' },
		{ icon: '🗓️', name: 'Calendar', keywords: ['calendar', 'schedule', 'plan', 'itinerary'], group: 'Travel & Trips' },
		{ icon: '📅', name: 'Calendar', keywords: ['calendar', 'date', 'schedule', 'booking'], group: 'Travel & Trips' },
		{ icon: '🎫', name: 'Ticket', keywords: ['ticket', 'admission', 'event', 'travel'], group: 'Travel & Trips' },
		{ icon: '🎟️', name: 'Admission Tickets', keywords: ['tickets', 'admission', 'event', 'attraction'], group: 'Travel & Trips' },

		// Love & Relationships
		{ icon: '❤️', name: 'Red Heart', keywords: ['heart', 'love', 'romance', 'valentine'], group: 'Love & Relationships' },
		{ icon: '💕', name: 'Two Hearts', keywords: ['hearts', 'love', 'romance', 'couple'], group: 'Love & Relationships' },
		{ icon: '💖', name: 'Sparkling Heart', keywords: ['heart', 'love', 'sparkle', 'romance'], group: 'Love & Relationships' },
		{ icon: '💗', name: 'Growing Heart', keywords: ['heart', 'love', 'growing', 'romance'], group: 'Love & Relationships' },
		{ icon: '💓', name: 'Beating Heart', keywords: ['heart', 'love', 'beating', 'pulse'], group: 'Love & Relationships' },
		{ icon: '💞', name: 'Revolving Hearts', keywords: ['hearts', 'love', 'revolving', 'romance'], group: 'Love & Relationships' },
		{ icon: '💘', name: 'Heart with Arrow', keywords: ['heart', 'arrow', 'cupid', 'love'], group: 'Love & Relationships' },
		{ icon: '💝', name: 'Heart with Ribbon', keywords: ['heart', 'gift', 'love', 'valentine'], group: 'Love & Relationships' },
		{ icon: '💟', name: 'Heart Decoration', keywords: ['heart', 'decoration', 'love', 'ornament'], group: 'Love & Relationships' },
		{ icon: '💌', name: 'Love Letter', keywords: ['love', 'letter', 'mail', 'romance'], group: 'Love & Relationships' },
		{ icon: '💑', name: 'Couple with Heart', keywords: ['couple', 'love', 'romance', 'relationship'], group: 'Love & Relationships' },
		{ icon: '💏', name: 'Kiss', keywords: ['kiss', 'love', 'romance', 'couple'], group: 'Love & Relationships' },
		{ icon: '👫', name: 'Man and Woman', keywords: ['couple', 'man', 'woman', 'relationship'], group: 'Love & Relationships' },
		{ icon: '👬', name: 'Two Men', keywords: ['men', 'couple', 'friends', 'relationship'], group: 'Love & Relationships' },
		{ icon: '👭', name: 'Two Women', keywords: ['women', 'couple', 'friends', 'relationship'], group: 'Love & Relationships' },
		{ icon: '🌹', name: 'Rose', keywords: ['rose', 'flower', 'love', 'romance'], group: 'Love & Relationships' },
		{ icon: '💐', name: 'Bouquet', keywords: ['bouquet', 'flowers', 'gift', 'romance'], group: 'Love & Relationships' },
		{ icon: '🌷', name: 'Tulip', keywords: ['tulip', 'flower', 'spring', 'romance'], group: 'Love & Relationships' },
		{ icon: '💍', name: 'Ring', keywords: ['ring', 'wedding', 'engagement', 'marriage'], group: 'Love & Relationships' },
		{ icon: '💒', name: 'Wedding', keywords: ['wedding', 'marriage', 'chapel', 'ceremony'], group: 'Love & Relationships' },
		{ icon: '🥂', name: 'Clinking Glasses', keywords: ['cheers', 'toast', 'celebration', 'champagne'], group: 'Love & Relationships' },
		{ icon: '🍾', name: 'Champagne', keywords: ['champagne', 'celebration', 'bottle', 'party'], group: 'Love & Relationships' },
		{ icon: '🕯️', name: 'Candle', keywords: ['candle', 'romantic', 'light', 'atmosphere'], group: 'Love & Relationships' },

		// Family & People
		{ icon: '👨‍👩‍👧‍👦', name: 'Family', keywords: ['family', 'parents', 'children', 'home'], group: 'Family & People' },
		{ icon: '👨‍👩‍👧', name: 'Family with Girl', keywords: ['family', 'parents', 'daughter', 'girl'], group: 'Family & People' },
		{ icon: '👨‍👩‍👦', name: 'Family with Boy', keywords: ['family', 'parents', 'son', 'boy'], group: 'Family & People' },
		{ icon: '👨‍👩‍👦‍👦', name: 'Family with Boys', keywords: ['family', 'parents', 'sons', 'boys'], group: 'Family & People' },
		{ icon: '👨‍👩‍👧‍👧', name: 'Family with Girls', keywords: ['family', 'parents', 'daughters', 'girls'], group: 'Family & People' },
		{ icon: '👶', name: 'Baby', keywords: ['baby', 'infant', 'child', 'newborn'], group: 'Family & People' },
		{ icon: '🍼', name: 'Baby Bottle', keywords: ['bottle', 'baby', 'milk', 'feeding'], group: 'Family & People' },
		{ icon: '👧', name: 'Girl', keywords: ['girl', 'child', 'daughter', 'young'], group: 'Family & People' },
		{ icon: '👦', name: 'Boy', keywords: ['boy', 'child', 'son', 'young'], group: 'Family & People' },
		{ icon: '👨', name: 'Man', keywords: ['man', 'male', 'adult', 'person'], group: 'Family & People' },
		{ icon: '👩', name: 'Woman', keywords: ['woman', 'female', 'adult', 'person'], group: 'Family & People' },
		{ icon: '👴', name: 'Old Man', keywords: ['old', 'man', 'elderly', 'grandfather'], group: 'Family & People' },
		{ icon: '👵', name: 'Old Woman', keywords: ['old', 'woman', 'elderly', 'grandmother'], group: 'Family & People' },
		{ icon: '👨‍🍼', name: 'Man Feeding Baby', keywords: ['man', 'baby', 'feeding', 'father'], group: 'Family & People' },
		{ icon: '👩‍🍼', name: 'Woman Feeding Baby', keywords: ['woman', 'baby', 'feeding', 'mother'], group: 'Family & People' },
		{ icon: '🤱', name: 'Breastfeeding', keywords: ['breastfeeding', 'mother', 'baby', 'nursing'], group: 'Family & People' },
		{ icon: '🤰', name: 'Pregnant Woman', keywords: ['pregnant', 'pregnancy', 'expecting', 'baby'], group: 'Family & People' },
		{ icon: '👼', name: 'Baby Angel', keywords: ['angel', 'baby', 'cherub', 'innocent'], group: 'Family & People' },
		{ icon: '🎂', name: 'Birthday Cake', keywords: ['birthday', 'cake', 'celebration', 'party'], group: 'Family & People' },
		{ icon: '🧸', name: 'Teddy Bear', keywords: ['teddy', 'bear', 'toy', 'children'], group: 'Family & People' },
		{ icon: '🎨', name: 'Art Palette', keywords: ['art', 'painting', 'creative', 'kids'], group: 'Family & People' },
		{ icon: '🧩', name: 'Puzzle', keywords: ['puzzle', 'game', 'kids', 'learning'], group: 'Family & People' },
		{ icon: '🏡', name: 'House with Garden', keywords: ['house', 'home', 'family', 'garden'], group: 'Family & People' },
		{ icon: '🏠', name: 'Home', keywords: ['home', 'house', 'family', 'residence'], group: 'Family & People' },
		{ icon: '👪', name: 'Family Icon', keywords: ['family', 'people', 'group', 'together'], group: 'Family & People' },
		{ icon: '🗣️', name: 'Speaking Head', keywords: ['speaking', 'talk', 'speech', 'voice'], group: 'Family & People' },
		{ icon: '👥', name: 'People', keywords: ['people', 'group', 'users', 'team'], group: 'Family & People' },

		// Animals & Pets
		{ icon: '🐶', name: 'Dog', keywords: ['dog', 'pet', 'puppy', 'animal'], group: 'Animals & Pets' },
		{ icon: '🐷', name: 'Pig', keywords: ['pig', 'piggy', 'animal', 'savings'], group: 'Animals & Pets' },
		{ icon: '🐾', name: 'Paw Prints', keywords: ['paw', 'prints', 'pet', 'animal'], group: 'Animals & Pets' },
		{ icon: '🦴', name: 'Bone', keywords: ['bone', 'dog', 'pet', 'treat'], group: 'Animals & Pets' },

		// Countries & Flags
		{ icon: '🇺🇸', name: 'United States', keywords: ['usa', 'america', 'united states', 'flag'], group: 'Countries & Flags' },
		{ icon: '🇬🇧', name: 'United Kingdom', keywords: ['uk', 'britain', 'england', 'flag'], group: 'Countries & Flags' },
		{ icon: '🇨🇦', name: 'Canada', keywords: ['canada', 'canadian', 'flag', 'maple'], group: 'Countries & Flags' },
		{ icon: '🇦🇺', name: 'Australia', keywords: ['australia', 'aussie', 'flag', 'oceania'], group: 'Countries & Flags' },
		{ icon: '🇯🇵', name: 'Japan', keywords: ['japan', 'japanese', 'flag', 'asia'], group: 'Countries & Flags' },
		{ icon: '🇨🇳', name: 'China', keywords: ['china', 'chinese', 'flag', 'asia'], group: 'Countries & Flags' },
		{ icon: '🇰🇷', name: 'South Korea', keywords: ['korea', 'korean', 'flag', 'asia'], group: 'Countries & Flags' },
		{ icon: '🇮🇳', name: 'India', keywords: ['india', 'indian', 'flag', 'asia'], group: 'Countries & Flags' },
		{ icon: '🇹🇭', name: 'Thailand', keywords: ['thailand', 'thai', 'flag', 'asia'], group: 'Countries & Flags' },
		{ icon: '🇸🇬', name: 'Singapore', keywords: ['singapore', 'singaporean', 'flag', 'asia'], group: 'Countries & Flags' },
		{ icon: '🇲🇾', name: 'Malaysia', keywords: ['malaysia', 'malaysian', 'flag', 'asia'], group: 'Countries & Flags' },
		{ icon: '🇮🇩', name: 'Indonesia', keywords: ['indonesia', 'indonesian', 'flag', 'asia'], group: 'Countries & Flags' },
		{ icon: '🇵🇭', name: 'Philippines', keywords: ['philippines', 'filipino', 'flag', 'asia'], group: 'Countries & Flags' },
		{ icon: '🇻🇳', name: 'Vietnam', keywords: ['vietnam', 'vietnamese', 'flag', 'asia'], group: 'Countries & Flags' },
		{ icon: '🇫🇷', name: 'France', keywords: ['france', 'french', 'flag', 'europe'], group: 'Countries & Flags' },
		{ icon: '🇩🇪', name: 'Germany', keywords: ['germany', 'german', 'flag', 'europe'], group: 'Countries & Flags' },
		{ icon: '🇮🇹', name: 'Italy', keywords: ['italy', 'italian', 'flag', 'europe'], group: 'Countries & Flags' },
		{ icon: '🇪🇸', name: 'Spain', keywords: ['spain', 'spanish', 'flag', 'europe'], group: 'Countries & Flags' },
		{ icon: '🇵🇹', name: 'Portugal', keywords: ['portugal', 'portuguese', 'flag', 'europe'], group: 'Countries & Flags' },
		{ icon: '🇳🇱', name: 'Netherlands', keywords: ['netherlands', 'dutch', 'holland', 'flag'], group: 'Countries & Flags' },
		{ icon: '🇧🇪', name: 'Belgium', keywords: ['belgium', 'belgian', 'flag', 'europe'], group: 'Countries & Flags' },
		{ icon: '🇨🇭', name: 'Switzerland', keywords: ['switzerland', 'swiss', 'flag', 'europe'], group: 'Countries & Flags' },
		{ icon: '🇦🇹', name: 'Austria', keywords: ['austria', 'austrian', 'flag', 'europe'], group: 'Countries & Flags' },
		{ icon: '🇸🇪', name: 'Sweden', keywords: ['sweden', 'swedish', 'flag', 'scandinavia'], group: 'Countries & Flags' },
		{ icon: '🇳🇴', name: 'Norway', keywords: ['norway', 'norwegian', 'flag', 'scandinavia'], group: 'Countries & Flags' },
		{ icon: '🇩🇰', name: 'Denmark', keywords: ['denmark', 'danish', 'flag', 'scandinavia'], group: 'Countries & Flags' },
		{ icon: '🇫🇮', name: 'Finland', keywords: ['finland', 'finnish', 'flag', 'scandinavia'], group: 'Countries & Flags' },
		{ icon: '🇮🇸', name: 'Iceland', keywords: ['iceland', 'icelandic', 'flag', 'nordic'], group: 'Countries & Flags' },
		{ icon: '🇮🇪', name: 'Ireland', keywords: ['ireland', 'irish', 'flag', 'europe'], group: 'Countries & Flags' },
		{ icon: '🇵🇱', name: 'Poland', keywords: ['poland', 'polish', 'flag', 'europe'], group: 'Countries & Flags' },
		{ icon: '🇷🇺', name: 'Russia', keywords: ['russia', 'russian', 'flag', 'europe'], group: 'Countries & Flags' },
		{ icon: '🇬🇷', name: 'Greece', keywords: ['greece', 'greek', 'flag', 'europe'], group: 'Countries & Flags' },
		{ icon: '🇹🇷', name: 'Turkey', keywords: ['turkey', 'turkish', 'flag', 'europe'], group: 'Countries & Flags' },
		{ icon: '🇨🇿', name: 'Czech Republic', keywords: ['czech', 'czechia', 'prague', 'flag'], group: 'Countries & Flags' },
		{ icon: '🇭🇺', name: 'Hungary', keywords: ['hungary', 'hungarian', 'flag', 'europe'], group: 'Countries & Flags' },
		{ icon: '🇷🇴', name: 'Romania', keywords: ['romania', 'romanian', 'flag', 'europe'], group: 'Countries & Flags' },
		{ icon: '🇧🇷', name: 'Brazil', keywords: ['brazil', 'brazilian', 'flag', 'south america'], group: 'Countries & Flags' },
		{ icon: '🇦🇷', name: 'Argentina', keywords: ['argentina', 'argentinian', 'flag', 'south america'], group: 'Countries & Flags' },
		{ icon: '🇨🇱', name: 'Chile', keywords: ['chile', 'chilean', 'flag', 'south america'], group: 'Countries & Flags' },
		{ icon: '🇨🇴', name: 'Colombia', keywords: ['colombia', 'colombian', 'flag', 'south america'], group: 'Countries & Flags' },
		{ icon: '🇵🇪', name: 'Peru', keywords: ['peru', 'peruvian', 'flag', 'south america'], group: 'Countries & Flags' },
		{ icon: '🇲🇽', name: 'Mexico', keywords: ['mexico', 'mexican', 'flag', 'north america'], group: 'Countries & Flags' },
		{ icon: '🇿🇦', name: 'South Africa', keywords: ['south africa', 'african', 'flag', 'africa'], group: 'Countries & Flags' },
		{ icon: '🇪🇬', name: 'Egypt', keywords: ['egypt', 'egyptian', 'flag', 'africa'], group: 'Countries & Flags' },
		{ icon: '🇰🇪', name: 'Kenya', keywords: ['kenya', 'kenyan', 'flag', 'africa'], group: 'Countries & Flags' },
		{ icon: '🇳🇬', name: 'Nigeria', keywords: ['nigeria', 'nigerian', 'flag', 'africa'], group: 'Countries & Flags' },
		{ icon: '🇲🇦', name: 'Morocco', keywords: ['morocco', 'moroccan', 'flag', 'africa'], group: 'Countries & Flags' },
		{ icon: '🇦🇪', name: 'UAE', keywords: ['uae', 'dubai', 'emirates', 'flag'], group: 'Countries & Flags' },
		{ icon: '🇸🇦', name: 'Saudi Arabia', keywords: ['saudi', 'arabia', 'flag', 'middle east'], group: 'Countries & Flags' },
		{ icon: '🇮🇱', name: 'Israel', keywords: ['israel', 'israeli', 'flag', 'middle east'], group: 'Countries & Flags' },
		{ icon: '🇳🇿', name: 'New Zealand', keywords: ['new zealand', 'kiwi', 'flag', 'oceania'], group: 'Countries & Flags' },
		{ icon: '🇭🇰', name: 'Hong Kong', keywords: ['hong kong', 'hk', 'flag', 'asia'], group: 'Countries & Flags' },
		{ icon: '🇹🇼', name: 'Taiwan', keywords: ['taiwan', 'taiwanese', 'flag', 'asia'], group: 'Countries & Flags' },
		{ icon: '🇲🇴', name: 'Macau', keywords: ['macau', 'macao', 'flag', 'asia'], group: 'Countries & Flags' },
		{ icon: '🇰🇭', name: 'Cambodia', keywords: ['cambodia', 'cambodian', 'flag', 'asia'], group: 'Countries & Flags' },
		{ icon: '🇱🇦', name: 'Laos', keywords: ['laos', 'lao', 'flag', 'asia'], group: 'Countries & Flags' },
		{ icon: '🇲🇲', name: 'Myanmar', keywords: ['myanmar', 'burma', 'flag', 'asia'], group: 'Countries & Flags' },
		{ icon: '🇧🇩', name: 'Bangladesh', keywords: ['bangladesh', 'bengali', 'flag', 'asia'], group: 'Countries & Flags' },
		{ icon: '🇵🇰', name: 'Pakistan', keywords: ['pakistan', 'pakistani', 'flag', 'asia'], group: 'Countries & Flags' },
		{ icon: '🇱🇰', name: 'Sri Lanka', keywords: ['sri lanka', 'lankan', 'flag', 'asia'], group: 'Countries & Flags' },
		{ icon: '🇳🇵', name: 'Nepal', keywords: ['nepal', 'nepalese', 'flag', 'asia'], group: 'Countries & Flags' },
		{ icon: '🇧🇳', name: 'Brunei', keywords: ['brunei', 'flag', 'asia', 'southeast'], group: 'Countries & Flags' },
		{ icon: '🇲🇻', name: 'Maldives', keywords: ['maldives', 'maldivian', 'flag', 'asia'], group: 'Countries & Flags' },
		{ icon: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', name: 'England', keywords: ['england', 'english', 'flag', 'uk'], group: 'Countries & Flags' },
		{ icon: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', name: 'Scotland', keywords: ['scotland', 'scottish', 'flag', 'uk'], group: 'Countries & Flags' },
		{ icon: '🏴󠁧󠁢󠁷󠁬󠁳󠁿', name: 'Wales', keywords: ['wales', 'welsh', 'flag', 'uk'], group: 'Countries & Flags' },
		{ icon: '🇪🇺', name: 'European Union', keywords: ['eu', 'europe', 'union', 'flag'], group: 'Countries & Flags' },
		{ icon: '🇺🇳', name: 'United Nations', keywords: ['un', 'united nations', 'international', 'flag'], group: 'Countries & Flags' },
		{ icon: '🌍', name: 'Globe Europe-Africa', keywords: ['globe', 'world', 'international', 'earth'], group: 'Countries & Flags' },
		{ icon: '🌎', name: 'Globe Americas', keywords: ['globe', 'world', 'international', 'earth'], group: 'Countries & Flags' },
		{ icon: '🌏', name: 'Globe Asia-Australia', keywords: ['globe', 'world', 'international', 'earth'], group: 'Countries & Flags' },
		{ icon: '🌐', name: 'Globe with Meridians', keywords: ['globe', 'world', 'international', 'web'], group: 'Countries & Flags' },
		{ icon: '🗺️', name: 'World Map', keywords: ['map', 'world', 'geography', 'travel'], group: 'Countries & Flags' },

		// Symbols & Misc
		{ icon: '✅', name: 'Check Mark', keywords: ['check', 'yes', 'done', 'complete'], group: 'Symbols & Misc' },
		{ icon: '❌', name: 'Cross Mark', keywords: ['cross', 'x', 'no', 'cancel'], group: 'Symbols & Misc' },
		{ icon: '⚠️', name: 'Warning', keywords: ['warning', 'caution', 'alert', 'attention'], group: 'Symbols & Misc' },
		{ icon: '❗', name: 'Exclamation', keywords: ['exclamation', 'important', 'alert', 'priority'], group: 'Symbols & Misc' },
		{ icon: '❓', name: 'Question', keywords: ['question', 'help', 'unknown', 'query'], group: 'Symbols & Misc' },
		{ icon: '🎉', name: 'Party Popper', keywords: ['party', 'celebrate', 'celebration', 'confetti'], group: 'Symbols & Misc' },
		{ icon: '🎊', name: 'Confetti Ball', keywords: ['confetti', 'celebration', 'party', 'festive'], group: 'Symbols & Misc' },
		{ icon: '🎈', name: 'Balloon', keywords: ['balloon', 'party', 'celebration', 'birthday'], group: 'Symbols & Misc' },
		{ icon: '🎀', name: 'Ribbon', keywords: ['ribbon', 'bow', 'decoration', 'gift'], group: 'Symbols & Misc' },
		{ icon: '⏰', name: 'Alarm Clock', keywords: ['clock', 'alarm', 'time', 'wake'], group: 'Symbols & Misc' },
		{ icon: '📅', name: 'Calendar', keywords: ['calendar', 'date', 'schedule', 'plan'], group: 'Symbols & Misc' },
		{ icon: '📆', name: 'Calendar Page', keywords: ['calendar', 'date', 'day', 'schedule'], group: 'Symbols & Misc' },
		{ icon: '🔔', name: 'Bell', keywords: ['bell', 'notification', 'alert', 'ring'], group: 'Symbols & Misc' },
		{ icon: '🔕', name: 'Bell Slash', keywords: ['bell', 'mute', 'silent', 'off'], group: 'Symbols & Misc' },
		{ icon: '📌', name: 'Pushpin', keywords: ['pin', 'pushpin', 'tack', 'attach'], group: 'Symbols & Misc' },
		{ icon: '📍', name: 'Location Pin', keywords: ['location', 'pin', 'map', 'place'], group: 'Symbols & Misc' },
	]
};
