import type { IconItem } from '$lib/components/ui/icon-combobox';

export const iconData: { icons: IconItem[] } = {
	icons: [
		// Money & Finance
		{ icon: '💰', name: 'Money Bag', keywords: ['money', 'cash', 'dollar', 'wealth'], group: 'Money & Finance' },
		{ icon: '💵', name: 'Dollar Bill', keywords: ['money', 'cash', 'dollar', 'currency'], group: 'Money & Finance' },
		{ icon: '💳', name: 'Credit Card', keywords: ['card', 'payment', 'credit', 'debit'], group: 'Money & Finance' },
		{ icon: '💸', name: 'Money with Wings', keywords: ['money', 'spending', 'expense', 'flying'], group: 'Money & Finance' },
		{ icon: '🏦', name: 'Bank', keywords: ['bank', 'building', 'finance', 'money'], group: 'Money & Finance' },
		{ icon: '💎', name: 'Gem', keywords: ['diamond', 'jewel', 'valuable', 'expensive'], group: 'Money & Finance' },
		{ icon: '🪙', name: 'Coin', keywords: ['money', 'currency', 'coin', 'gold'], group: 'Money & Finance' },
		{ icon: '💴', name: 'Yen Bill', keywords: ['yen', 'currency', 'japan', 'money'], group: 'Money & Finance' },
		{ icon: '💶', name: 'Euro Bill', keywords: ['euro', 'currency', 'europe', 'money'], group: 'Money & Finance' },
		{ icon: '💷', name: 'Pound Bill', keywords: ['pound', 'currency', 'uk', 'money'], group: 'Money & Finance' },

		// Buildings & Places
		{ icon: '🏠', name: 'House', keywords: ['home', 'house', 'building', 'rent'], group: 'Buildings & Places' },
		{ icon: '🏢', name: 'Office Building', keywords: ['office', 'work', 'building', 'business'], group: 'Buildings & Places' },
		{ icon: '🏪', name: 'Store', keywords: ['shop', 'store', 'shopping', 'retail'], group: 'Buildings & Places' },
		{ icon: '🏫', name: 'School', keywords: ['school', 'education', 'learning', 'building'], group: 'Buildings & Places' },
		{ icon: '🏥', name: 'Hospital', keywords: ['hospital', 'health', 'medical', 'doctor'], group: 'Buildings & Places' },
		{ icon: '🏨', name: 'Hotel', keywords: ['hotel', 'accommodation', 'lodging', 'travel'], group: 'Buildings & Places' },
		{ icon: '🏛️', name: 'Classical Building', keywords: ['museum', 'government', 'monument', 'building'], group: 'Buildings & Places' },
		{ icon: '⛪', name: 'Church', keywords: ['church', 'religion', 'building', 'worship'], group: 'Buildings & Places' },
		{ icon: '🕌', name: 'Mosque', keywords: ['mosque', 'religion', 'islam', 'worship'], group: 'Buildings & Places' },

		// Transportation
		{ icon: '🚗', name: 'Car', keywords: ['car', 'vehicle', 'auto', 'transport'], group: 'Transportation' },
		{ icon: '🚕', name: 'Taxi', keywords: ['taxi', 'cab', 'transport', 'ride'], group: 'Transportation' },
		{ icon: '🚙', name: 'SUV', keywords: ['suv', 'car', 'vehicle', 'auto'], group: 'Transportation' },
		{ icon: '🚌', name: 'Bus', keywords: ['bus', 'transport', 'public', 'travel'], group: 'Transportation' },
		{ icon: '🚎', name: 'Trolleybus', keywords: ['bus', 'trolley', 'transport', 'public'], group: 'Transportation' },
		{ icon: '🚐', name: 'Minibus', keywords: ['minibus', 'van', 'transport', 'vehicle'], group: 'Transportation' },
		{ icon: '🚑', name: 'Ambulance', keywords: ['ambulance', 'emergency', 'medical', 'hospital'], group: 'Transportation' },
		{ icon: '🚒', name: 'Fire Engine', keywords: ['fire', 'truck', 'emergency', 'rescue'], group: 'Transportation' },
		{ icon: '🚓', name: 'Police Car', keywords: ['police', 'cop', 'law', 'emergency'], group: 'Transportation' },
		{ icon: '🚲', name: 'Bicycle', keywords: ['bike', 'bicycle', 'cycling', 'transport'], group: 'Transportation' },
		{ icon: '🛵', name: 'Motor Scooter', keywords: ['scooter', 'motorcycle', 'moped', 'bike'], group: 'Transportation' },
		{ icon: '🏍️', name: 'Motorcycle', keywords: ['motorcycle', 'bike', 'motor', 'transport'], group: 'Transportation' },
		{ icon: '✈️', name: 'Airplane', keywords: ['airplane', 'plane', 'flight', 'travel'], group: 'Transportation' },
		{ icon: '🚁', name: 'Helicopter', keywords: ['helicopter', 'chopper', 'flight', 'aircraft'], group: 'Transportation' },
		{ icon: '🚂', name: 'Train', keywords: ['train', 'railway', 'transport', 'locomotive'], group: 'Transportation' },
		{ icon: '🚇', name: 'Metro', keywords: ['metro', 'subway', 'underground', 'train'], group: 'Transportation' },
		{ icon: '🚆', name: 'Train', keywords: ['train', 'railway', 'commute', 'transport'], group: 'Transportation' },
		{ icon: '🚊', name: 'Tram', keywords: ['tram', 'streetcar', 'trolley', 'transport'], group: 'Transportation' },
		{ icon: '🚢', name: 'Ship', keywords: ['ship', 'boat', 'cruise', 'ocean'], group: 'Transportation' },
		{ icon: '⛴️', name: 'Ferry', keywords: ['ferry', 'boat', 'water', 'transport'], group: 'Transportation' },
		{ icon: '🚤', name: 'Speedboat', keywords: ['boat', 'speedboat', 'water', 'fast'], group: 'Transportation' },

		// Food & Dining
		{ icon: '🍔', name: 'Hamburger', keywords: ['burger', 'food', 'fast food', 'meal'], group: 'Food & Dining' },
		{ icon: '🍕', name: 'Pizza', keywords: ['pizza', 'food', 'italian', 'meal'], group: 'Food & Dining' },
		{ icon: '🍟', name: 'Fries', keywords: ['fries', 'french fries', 'food', 'fast food'], group: 'Food & Dining' },
		{ icon: '🌭', name: 'Hot Dog', keywords: ['hot dog', 'food', 'sausage', 'fast food'], group: 'Food & Dining' },
		{ icon: '🥗', name: 'Salad', keywords: ['salad', 'healthy', 'vegetables', 'food'], group: 'Food & Dining' },
		{ icon: '🍝', name: 'Pasta', keywords: ['pasta', 'spaghetti', 'italian', 'food'], group: 'Food & Dining' },
		{ icon: '🍜', name: 'Noodles', keywords: ['noodles', 'ramen', 'soup', 'asian'], group: 'Food & Dining' },
		{ icon: '🍱', name: 'Bento Box', keywords: ['bento', 'lunch', 'japanese', 'food'], group: 'Food & Dining' },
		{ icon: '🍛', name: 'Curry', keywords: ['curry', 'rice', 'indian', 'food'], group: 'Food & Dining' },
		{ icon: '🍲', name: 'Stew', keywords: ['stew', 'pot', 'soup', 'food'], group: 'Food & Dining' },
		{ icon: '🥘', name: 'Paella', keywords: ['paella', 'rice', 'spanish', 'food'], group: 'Food & Dining' },
		{ icon: '🍣', name: 'Sushi', keywords: ['sushi', 'japanese', 'fish', 'food'], group: 'Food & Dining' },
		{ icon: '🍱', name: 'Lunch Box', keywords: ['lunch', 'box', 'meal', 'food'], group: 'Food & Dining' },
		{ icon: '🥪', name: 'Sandwich', keywords: ['sandwich', 'bread', 'meal', 'food'], group: 'Food & Dining' },
		{ icon: '🌮', name: 'Taco', keywords: ['taco', 'mexican', 'food', 'meal'], group: 'Food & Dining' },
		{ icon: '🌯', name: 'Burrito', keywords: ['burrito', 'mexican', 'wrap', 'food'], group: 'Food & Dining' },
		{ icon: '🥙', name: 'Kebab', keywords: ['kebab', 'pita', 'middle eastern', 'food'], group: 'Food & Dining' },
		{ icon: '🍖', name: 'Meat', keywords: ['meat', 'bone', 'food', 'protein'], group: 'Food & Dining' },
		{ icon: '🍗', name: 'Chicken', keywords: ['chicken', 'poultry', 'drumstick', 'food'], group: 'Food & Dining' },
		{ icon: '☕', name: 'Coffee', keywords: ['coffee', 'cafe', 'drink', 'hot'], group: 'Food & Dining' },
		{ icon: '🍺', name: 'Beer', keywords: ['beer', 'drink', 'alcohol', 'beverage'], group: 'Food & Dining' },
		{ icon: '🍷', name: 'Wine', keywords: ['wine', 'drink', 'alcohol', 'glass'], group: 'Food & Dining' },
		{ icon: '🍰', name: 'Cake', keywords: ['cake', 'dessert', 'sweet', 'birthday'], group: 'Food & Dining' },
		{ icon: '🍪', name: 'Cookie', keywords: ['cookie', 'dessert', 'sweet', 'snack'], group: 'Food & Dining' },
		{ icon: '🍩', name: 'Donut', keywords: ['donut', 'doughnut', 'dessert', 'sweet'], group: 'Food & Dining' },
		{ icon: '🍦', name: 'Ice Cream', keywords: ['ice cream', 'dessert', 'sweet', 'frozen'], group: 'Food & Dining' },

		// Shopping & Retail
		{ icon: '🛒', name: 'Shopping Cart', keywords: ['cart', 'shopping', 'grocery', 'store'], group: 'Shopping & Retail' },
		{ icon: '🛍️', name: 'Shopping Bags', keywords: ['shopping', 'bags', 'purchase', 'retail'], group: 'Shopping & Retail' },
		{ icon: '🎁', name: 'Gift', keywords: ['gift', 'present', 'wrapped', 'surprise'], group: 'Shopping & Retail' },
		{ icon: '🏷️', name: 'Label', keywords: ['label', 'tag', 'price', 'sale'], group: 'Shopping & Retail' },
		{ icon: '👕', name: 'T-Shirt', keywords: ['shirt', 'clothes', 'clothing', 'wear'], group: 'Shopping & Retail' },
		{ icon: '👔', name: 'Necktie', keywords: ['tie', 'formal', 'clothes', 'business'], group: 'Shopping & Retail' },
		{ icon: '👗', name: 'Dress', keywords: ['dress', 'clothes', 'clothing', 'fashion'], group: 'Shopping & Retail' },
		{ icon: '👠', name: 'High Heel', keywords: ['shoe', 'heel', 'fashion', 'footwear'], group: 'Shopping & Retail' },
		{ icon: '👟', name: 'Sneaker', keywords: ['sneaker', 'shoe', 'sport', 'footwear'], group: 'Shopping & Retail' },

		// Entertainment & Hobbies
		{ icon: '🎮', name: 'Game Controller', keywords: ['game', 'gaming', 'video', 'play'], group: 'Entertainment & Hobbies' },
		{ icon: '🎯', name: 'Target', keywords: ['target', 'bullseye', 'goal', 'aim'], group: 'Entertainment & Hobbies' },
		{ icon: '🎲', name: 'Dice', keywords: ['dice', 'game', 'random', 'board game'], group: 'Entertainment & Hobbies' },
		{ icon: '🎰', name: 'Slot Machine', keywords: ['slot', 'casino', 'gambling', 'luck'], group: 'Entertainment & Hobbies' },
		{ icon: '🎬', name: 'Movie', keywords: ['movie', 'film', 'cinema', 'entertainment'], group: 'Entertainment & Hobbies' },
		{ icon: '🎭', name: 'Theater', keywords: ['theater', 'drama', 'performance', 'arts'], group: 'Entertainment & Hobbies' },
		{ icon: '🎨', name: 'Art', keywords: ['art', 'paint', 'palette', 'creative'], group: 'Entertainment & Hobbies' },
		{ icon: '🎪', name: 'Circus', keywords: ['circus', 'tent', 'entertainment', 'show'], group: 'Entertainment & Hobbies' },
		{ icon: '🎸', name: 'Guitar', keywords: ['guitar', 'music', 'instrument', 'rock'], group: 'Entertainment & Hobbies' },
		{ icon: '🎹', name: 'Piano', keywords: ['piano', 'music', 'instrument', 'keys'], group: 'Entertainment & Hobbies' },
		{ icon: '🎵', name: 'Music Note', keywords: ['music', 'note', 'song', 'melody'], group: 'Entertainment & Hobbies' },
		{ icon: '🎤', name: 'Microphone', keywords: ['microphone', 'mic', 'singing', 'karaoke'], group: 'Entertainment & Hobbies' },
		{ icon: '🎧', name: 'Headphones', keywords: ['headphones', 'music', 'audio', 'listen'], group: 'Entertainment & Hobbies' },
		{ icon: '📷', name: 'Camera', keywords: ['camera', 'photo', 'picture', 'photography'], group: 'Entertainment & Hobbies' },
		{ icon: '📺', name: 'Television', keywords: ['tv', 'television', 'screen', 'watch'], group: 'Entertainment & Hobbies' },
		{ icon: '🏀', name: 'Basketball', keywords: ['basketball', 'sport', 'ball', 'game'], group: 'Entertainment & Hobbies' },
		{ icon: '⚽', name: 'Soccer Ball', keywords: ['soccer', 'football', 'sport', 'ball'], group: 'Entertainment & Hobbies' },
		{ icon: '🏈', name: 'Football', keywords: ['football', 'american', 'sport', 'ball'], group: 'Entertainment & Hobbies' },
		{ icon: '⚾', name: 'Baseball', keywords: ['baseball', 'sport', 'ball', 'game'], group: 'Entertainment & Hobbies' },
		{ icon: '🎾', name: 'Tennis', keywords: ['tennis', 'sport', 'ball', 'racket'], group: 'Entertainment & Hobbies' },
		{ icon: '🏐', name: 'Volleyball', keywords: ['volleyball', 'sport', 'ball', 'beach'], group: 'Entertainment & Hobbies' },
		{ icon: '🏊', name: 'Swimming', keywords: ['swimming', 'pool', 'sport', 'water'], group: 'Entertainment & Hobbies' },
		{ icon: '🏋️', name: 'Weightlifting', keywords: ['gym', 'workout', 'fitness', 'weight'], group: 'Entertainment & Hobbies' },
		{ icon: '🧘', name: 'Yoga', keywords: ['yoga', 'meditation', 'wellness', 'fitness'], group: 'Entertainment & Hobbies' },

		// Technology & Devices
		{ icon: '📱', name: 'Phone', keywords: ['phone', 'mobile', 'smartphone', 'cell'], group: 'Technology & Devices' },
		{ icon: '💻', name: 'Laptop', keywords: ['laptop', 'computer', 'pc', 'work'], group: 'Technology & Devices' },
		{ icon: '🖥️', name: 'Desktop', keywords: ['desktop', 'computer', 'monitor', 'pc'], group: 'Technology & Devices' },
		{ icon: '⌨️', name: 'Keyboard', keywords: ['keyboard', 'typing', 'computer', 'input'], group: 'Technology & Devices' },
		{ icon: '🖱️', name: 'Mouse', keywords: ['mouse', 'computer', 'click', 'pointer'], group: 'Technology & Devices' },
		{ icon: '🖨️', name: 'Printer', keywords: ['printer', 'print', 'office', 'paper'], group: 'Technology & Devices' },
		{ icon: '📡', name: 'Satellite', keywords: ['satellite', 'antenna', 'signal', 'communication'], group: 'Technology & Devices' },
		{ icon: '🔋', name: 'Battery', keywords: ['battery', 'power', 'charge', 'energy'], group: 'Technology & Devices' },
		{ icon: '🔌', name: 'Electric Plug', keywords: ['plug', 'electric', 'power', 'outlet'], group: 'Technology & Devices' },
		{ icon: '💡', name: 'Light Bulb', keywords: ['bulb', 'light', 'idea', 'electricity'], group: 'Technology & Devices' },

		// Health & Medical
		{ icon: '💊', name: 'Pill', keywords: ['pill', 'medicine', 'drug', 'health'], group: 'Health & Medical' },
		{ icon: '💉', name: 'Syringe', keywords: ['syringe', 'injection', 'vaccine', 'medical'], group: 'Health & Medical' },
		{ icon: '🩺', name: 'Stethoscope', keywords: ['stethoscope', 'doctor', 'medical', 'health'], group: 'Health & Medical' },
		{ icon: '🩹', name: 'Bandage', keywords: ['bandage', 'adhesive', 'injury', 'medical'], group: 'Health & Medical' },
		{ icon: '🌡️', name: 'Thermometer', keywords: ['thermometer', 'temperature', 'fever', 'health'], group: 'Health & Medical' },
		{ icon: '🧴', name: 'Lotion', keywords: ['lotion', 'cream', 'skincare', 'bottle'], group: 'Health & Medical' },
		{ icon: '💆', name: 'Massage', keywords: ['massage', 'spa', 'relax', 'therapy'], group: 'Health & Medical' },
		{ icon: '🧘', name: 'Meditation', keywords: ['meditation', 'yoga', 'wellness', 'peace'], group: 'Health & Medical' },

		// Education & Work
		{ icon: '📚', name: 'Books', keywords: ['books', 'reading', 'library', 'study'], group: 'Education & Work' },
		{ icon: '📖', name: 'Book', keywords: ['book', 'reading', 'study', 'learn'], group: 'Education & Work' },
		{ icon: '📝', name: 'Memo', keywords: ['memo', 'note', 'writing', 'document'], group: 'Education & Work' },
		{ icon: '✏️', name: 'Pencil', keywords: ['pencil', 'writing', 'draw', 'school'], group: 'Education & Work' },
		{ icon: '🖊️', name: 'Pen', keywords: ['pen', 'writing', 'office', 'document'], group: 'Education & Work' },
		{ icon: '📄', name: 'Document', keywords: ['document', 'paper', 'file', 'page'], group: 'Education & Work' },
		{ icon: '📁', name: 'Folder', keywords: ['folder', 'file', 'organize', 'documents'], group: 'Education & Work' },
		{ icon: '📊', name: 'Chart', keywords: ['chart', 'graph', 'statistics', 'data'], group: 'Education & Work' },
		{ icon: '📈', name: 'Growth Chart', keywords: ['chart', 'growth', 'increase', 'trend'], group: 'Education & Work' },
		{ icon: '📉', name: 'Decline Chart', keywords: ['chart', 'decline', 'decrease', 'down'], group: 'Education & Work' },
		{ icon: '🎓', name: 'Graduation Cap', keywords: ['graduation', 'education', 'school', 'degree'], group: 'Education & Work' },
		{ icon: '🔬', name: 'Microscope', keywords: ['microscope', 'science', 'lab', 'research'], group: 'Education & Work' },
		{ icon: '🔭', name: 'Telescope', keywords: ['telescope', 'astronomy', 'space', 'science'], group: 'Education & Work' },
		{ icon: '📐', name: 'Triangle Ruler', keywords: ['ruler', 'triangle', 'math', 'geometry'], group: 'Education & Work' },
		{ icon: '📏', name: 'Ruler', keywords: ['ruler', 'measure', 'school', 'straight'], group: 'Education & Work' },
		{ icon: '💼', name: 'Briefcase', keywords: ['briefcase', 'business', 'work', 'office'], group: 'Education & Work' },

		// Utilities & Services
		{ icon: '🔧', name: 'Wrench', keywords: ['wrench', 'tool', 'repair', 'fix'], group: 'Utilities & Services' },
		{ icon: '🔨', name: 'Hammer', keywords: ['hammer', 'tool', 'build', 'fix'], group: 'Utilities & Services' },
		{ icon: '🪛', name: 'Screwdriver', keywords: ['screwdriver', 'tool', 'repair', 'fix'], group: 'Utilities & Services' },
		{ icon: '⚡', name: 'Lightning', keywords: ['lightning', 'electric', 'power', 'energy'], group: 'Utilities & Services' },
		{ icon: '🔥', name: 'Fire', keywords: ['fire', 'flame', 'hot', 'heat'], group: 'Utilities & Services' },
		{ icon: '💧', name: 'Water Drop', keywords: ['water', 'drop', 'liquid', 'utility'], group: 'Utilities & Services' },
		{ icon: '🚿', name: 'Shower', keywords: ['shower', 'bath', 'water', 'clean'], group: 'Utilities & Services' },
		{ icon: '🚽', name: 'Toilet', keywords: ['toilet', 'bathroom', 'wc', 'restroom'], group: 'Utilities & Services' },
		{ icon: '📞', name: 'Telephone', keywords: ['phone', 'telephone', 'call', 'contact'], group: 'Utilities & Services' },
		{ icon: '📧', name: 'Email', keywords: ['email', 'mail', 'message', 'inbox'], group: 'Utilities & Services' },
		{ icon: '📮', name: 'Mailbox', keywords: ['mailbox', 'post', 'mail', 'letter'], group: 'Utilities & Services' },
		{ icon: '🔒', name: 'Lock', keywords: ['lock', 'secure', 'security', 'safe'], group: 'Utilities & Services' },
		{ icon: '🔑', name: 'Key', keywords: ['key', 'unlock', 'access', 'security'], group: 'Utilities & Services' },
		{ icon: '🗑️', name: 'Trash', keywords: ['trash', 'garbage', 'delete', 'waste'], group: 'Utilities & Services' },
		{ icon: '♻️', name: 'Recycle', keywords: ['recycle', 'reuse', 'green', 'environment'], group: 'Utilities & Services' },

		// Nature & Weather
		{ icon: '🌞', name: 'Sun', keywords: ['sun', 'sunny', 'day', 'bright'], group: 'Nature & Weather' },
		{ icon: '🌙', name: 'Moon', keywords: ['moon', 'night', 'lunar', 'crescent'], group: 'Nature & Weather' },
		{ icon: '⭐', name: 'Star', keywords: ['star', 'night', 'shine', 'favorite'], group: 'Nature & Weather' },
		{ icon: '☀️', name: 'Sunshine', keywords: ['sun', 'sunny', 'bright', 'weather'], group: 'Nature & Weather' },
		{ icon: '⛅', name: 'Cloudy', keywords: ['cloud', 'cloudy', 'weather', 'overcast'], group: 'Nature & Weather' },
		{ icon: '🌧️', name: 'Rain', keywords: ['rain', 'rainy', 'weather', 'wet'], group: 'Nature & Weather' },
		{ icon: '⛈️', name: 'Storm', keywords: ['storm', 'thunder', 'lightning', 'weather'], group: 'Nature & Weather' },
		{ icon: '🌨️', name: 'Snow', keywords: ['snow', 'snowy', 'winter', 'cold'], group: 'Nature & Weather' },
		{ icon: '🌪️', name: 'Tornado', keywords: ['tornado', 'cyclone', 'storm', 'weather'], group: 'Nature & Weather' },
		{ icon: '🌈', name: 'Rainbow', keywords: ['rainbow', 'colors', 'weather', 'colorful'], group: 'Nature & Weather' },
		{ icon: '🌳', name: 'Tree', keywords: ['tree', 'nature', 'plant', 'green'], group: 'Nature & Weather' },
		{ icon: '🌲', name: 'Pine Tree', keywords: ['pine', 'tree', 'forest', 'evergreen'], group: 'Nature & Weather' },
		{ icon: '🌴', name: 'Palm Tree', keywords: ['palm', 'tree', 'tropical', 'beach'], group: 'Nature & Weather' },
		{ icon: '🌵', name: 'Cactus', keywords: ['cactus', 'desert', 'plant', 'succulent'], group: 'Nature & Weather' },
		{ icon: '🌺', name: 'Flower', keywords: ['flower', 'blossom', 'nature', 'plant'], group: 'Nature & Weather' },
		{ icon: '🌻', name: 'Sunflower', keywords: ['sunflower', 'flower', 'yellow', 'nature'], group: 'Nature & Weather' },
		{ icon: '🌹', name: 'Rose', keywords: ['rose', 'flower', 'love', 'romance'], group: 'Nature & Weather' },

		// Symbols & Misc
		{ icon: '✅', name: 'Check Mark', keywords: ['check', 'yes', 'done', 'complete'], group: 'Symbols & Misc' },
		{ icon: '❌', name: 'Cross Mark', keywords: ['cross', 'x', 'no', 'cancel'], group: 'Symbols & Misc' },
		{ icon: '⚠️', name: 'Warning', keywords: ['warning', 'caution', 'alert', 'attention'], group: 'Symbols & Misc' },
		{ icon: '❗', name: 'Exclamation', keywords: ['exclamation', 'important', 'alert', 'priority'], group: 'Symbols & Misc' },
		{ icon: '❓', name: 'Question', keywords: ['question', 'help', 'unknown', 'query'], group: 'Symbols & Misc' },
		{ icon: '🎉', name: 'Party Popper', keywords: ['party', 'celebrate', 'celebration', 'confetti'], group: 'Symbols & Misc' },
		{ icon: '🎊', name: 'Confetti Ball', keywords: ['confetti', 'celebration', 'party', 'festive'], group: 'Symbols & Misc' },
		{ icon: '🎈', name: 'Balloon', keywords: ['balloon', 'party', 'celebration', 'birthday'], group: 'Symbols & Misc' },
		{ icon: '🎀', name: 'Ribbon', keywords: ['ribbon', 'bow', 'decoration', 'gift'], group: 'Symbols & Misc' },
		{ icon: '🏆', name: 'Trophy', keywords: ['trophy', 'award', 'win', 'champion'], group: 'Symbols & Misc' },
		{ icon: '🥇', name: 'Gold Medal', keywords: ['medal', 'gold', 'first', 'winner'], group: 'Symbols & Misc' },
		{ icon: '🥈', name: 'Silver Medal', keywords: ['medal', 'silver', 'second', 'runner-up'], group: 'Symbols & Misc' },
		{ icon: '🥉', name: 'Bronze Medal', keywords: ['medal', 'bronze', 'third', 'podium'], group: 'Symbols & Misc' },
		{ icon: '⏰', name: 'Alarm Clock', keywords: ['clock', 'alarm', 'time', 'wake'], group: 'Symbols & Misc' },
		{ icon: '⌚', name: 'Watch', keywords: ['watch', 'time', 'clock', 'wrist'], group: 'Symbols & Misc' },
		{ icon: '📅', name: 'Calendar', keywords: ['calendar', 'date', 'schedule', 'plan'], group: 'Symbols & Misc' },
		{ icon: '📆', name: 'Calendar Page', keywords: ['calendar', 'date', 'day', 'schedule'], group: 'Symbols & Misc' },
		{ icon: '🔔', name: 'Bell', keywords: ['bell', 'notification', 'alert', 'ring'], group: 'Symbols & Misc' },
		{ icon: '🔕', name: 'Bell Slash', keywords: ['bell', 'mute', 'silent', 'off'], group: 'Symbols & Misc' },
		{ icon: '📌', name: 'Pushpin', keywords: ['pin', 'pushpin', 'tack', 'attach'], group: 'Symbols & Misc' },
		{ icon: '📍', name: 'Location Pin', keywords: ['location', 'pin', 'map', 'place'], group: 'Symbols & Misc' },
		{ icon: '🎯', name: 'Bullseye', keywords: ['target', 'goal', 'aim', 'focus'], group: 'Symbols & Misc' },
	]
};
